package dev.typetype.android.domain.server

data class Server(
    val id: String,
    val baseUrl: String,
    val displayName: String,
    val addedAt: Long,
    val tagline: String? = null,
    val version: String = "",
    val revision: String = "",
    val apiVersion: Int = 0,
    val logoUrl: String? = null,
    val bannerUrl: String? = null,
    val supportedServices: List<Int> = emptyList(),
    val minAndroidClientVersion: String? = null,
    val registrationAllowed: Boolean = false,
    val guestAllowed: Boolean = false,
    val localLoginEnabled: Boolean = true,
    val oidcEnabled: Boolean = false,
    val oidcProviderName: String? = null,
    val oidcAutoRedirect: Boolean = false,
    val youtubeRemoteLoginEnabled: Boolean = false,
    val youtubeRemoteLoginReady: Boolean = false,
    val youtubeRemoteLoginUnavailableReason: String? = null,
)
