package dev.typetype.android.feature.player

import androidx.annotation.OptIn
import androidx.media3.common.util.UnstableApi
import androidx.test.ext.junit.runners.AndroidJUnit4
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.domain.stream.SubtitleRepository
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

@OptIn(UnstableApi::class)
@RunWith(AndroidJUnit4::class)
class PlayerSubtitleCueLoaderTest {
    @Test
    fun webvttIsParsedIntoTimedCues() = runBlocking {
        val loader = PlayerSubtitleCueLoader(
            repository = object : SubtitleRepository {
                override suspend fun load(source: StreamSubtitleSource) = Result.success(
                    """
                    WEBVTT

                    00:00:01.000 --> 00:00:02.500
                    Hello from TypeType
                    """.trimIndent().encodeToByteArray(),
                )
            },
        )

        val cues = loader.load(subtitle()).getOrThrow()

        assertEquals(1, cues.size)
        assertEquals(1_000_000L, cues.single().startTimeUs)
        assertEquals(1_500_000L, cues.single().durationUs)
        assertTrue(cues.single().cues.single().text.toString().contains("Hello from TypeType"))
    }

    private fun subtitle() = StreamSubtitleSource(
        url = "https://instance.example/api/proxy?track=en",
        mimeType = "text/vtt",
        languageTag = "en",
        displayLanguageName = "English",
        isAutoGenerated = false,
    )
}
