package dev.typetype.android.feature.player

import androidx.annotation.OptIn
import androidx.media3.common.util.UnstableApi
import androidx.test.ext.junit.runners.AndroidJUnit4
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.domain.stream.SubtitleRepository
import dev.typetype.android.feature.player.components.activeAt
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

@OptIn(UnstableApi::class)
@RunWith(AndroidJUnit4::class)
class PlayerSubtitleCueLoaderTest {
    @Test
    fun ttmlIsParsedIntoTimedCuesAcrossSeekPositions() = runBlocking {
        val loader = loader(
            mapOf(
                "manual" to ttml(
                    firstText = "Manual opening",
                    secondText = "Manual after seek",
                ),
            ),
        )

        val cues = loader.load(subtitle("manual", isAutoGenerated = false)).getOrThrow()

        assertEquals(listOf("Manual opening"), cues.activeTextAt(1_500_000L))
        assertEquals(emptyList<String>(), cues.activeTextAt(4_000_000L))
        assertEquals(listOf("Manual after seek"), cues.activeTextAt(7_000_000L))
    }

    @Test
    fun switchingManualAndAutomaticTracksLoadsTheSelectedEndpoint() = runBlocking {
        val loader = loader(
            mapOf(
                "manual" to ttml("Manual track", "Manual later"),
                "auto" to ttml("Automatic track", "Automatic later"),
            ),
        )

        val manual = loader.load(subtitle("manual", isAutoGenerated = false)).getOrThrow()
        val automatic = loader.load(subtitle("auto", isAutoGenerated = true)).getOrThrow()

        assertEquals(listOf("Manual track"), manual.activeTextAt(1_500_000L))
        assertEquals(listOf("Automatic track"), automatic.activeTextAt(1_500_000L))
        assertTrue(manual != automatic)
    }

    private fun loader(fixtures: Map<String, ByteArray>) = PlayerSubtitleCueLoader(
        repository = object : SubtitleRepository {
            override suspend fun load(source: StreamSubtitleSource): Result<ByteArray> =
                fixtures[source.trackId]?.let(Result.Companion::success)
                    ?: Result.failure(IllegalArgumentException("Unknown subtitle track"))
        },
    )

    private fun subtitle(trackId: String, isAutoGenerated: Boolean) = StreamSubtitleSource(
        url = "https://instance.example/api/subtitles/youtube/video-id" +
            "?language=en&variant=$trackId&format=ttml",
        mimeType = "application/ttml+xml",
        languageTag = "en",
        displayLanguageName = "English",
        isAutoGenerated = isAutoGenerated,
        trackId = trackId,
    )

    private fun ttml(firstText: String, secondText: String): ByteArray =
        """
        <tt xmlns="http://www.w3.org/ns/ttml">
          <body><div>
            <p begin="00:00:01.000" end="00:00:03.000">$firstText</p>
            <p begin="00:00:06.000" end="00:00:08.000">$secondText</p>
          </div></body>
        </tt>
        """.trimIndent().encodeToByteArray()

    private fun List<androidx.media3.extractor.text.CuesWithTiming>.activeTextAt(
        positionUs: Long,
    ): List<String> = activeAt(positionUs).map { it.text.toString() }
}
