package dev.typetype.android.feature.player

import androidx.media3.common.MediaItem
import androidx.test.ext.junit.runners.AndroidJUnit4
import dev.typetype.android.domain.stream.SabrPlaybackBinding
import dev.typetype.android.domain.stream.SabrPlaybackSession
import dev.typetype.android.domain.stream.SabrPlaybackTarget
import dev.typetype.android.domain.stream.StreamRequestScope
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.domain.stream.sourceKey
import dev.typetype.android.services.MergedStreamMediaKeys
import dev.typetype.android.services.requireSabrTransportScope
import dev.typetype.android.services.sabrPlaybackSeekState
import dev.typetype.android.services.streamRequestScope
import dev.typetype.android.services.toSubtitleConfigurations
import dev.typetype.android.services.withSabrPlayback
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class SabrPlaybackSourceAndroidTest {
    @Test
    fun everySubtitleTrackIsAttachedBeforePlaybackSelection() {
        val subtitles = listOf(
            subtitle("en", "English", autoGenerated = false),
            subtitle("en", "English auto-generated", autoGenerated = true),
            subtitle("fr", "French", autoGenerated = false),
        )

        val configurations = subtitles.toSubtitleConfigurations()

        assertEquals(3, configurations.size)
        assertEquals(listOf("en:false", "en:true", "fr:false"), configurations.map { it.id })
        assertEquals(subtitles.map { it.url }, configurations.map { it.uri.toString() })
    }

    @Test
    fun preparedSessionMetadataSurvivesMediaItemRoundTrip() {
        val requestedKey = "sabr:video:137:140:en.0"
        val acceptedTarget = target(
            StreamRequestScope(
                serverId = "server",
                accountId = "account",
                baseUrl = "https://instance.example/api/",
            ),
            videoItag = 136,
        )
        val acceptedKey = acceptedTarget.sourceKey
        val playbackUri = "typetype-sabr://playback/session"
        val scope = acceptedTarget.requestScope
        val prepared = PlayableSource(
            url = playbackUri,
            mimeType = "application/x-typetype-sabr",
            sourceKey = acceptedKey,
            sabrRequestKey = requestedKey,
            sabrBinding = SabrPlaybackBinding("session", 3L, 136, 140, "en.0"),
            sabrTarget = acceptedTarget,
        )
        val mediaItem = MediaItem.Builder()
            .setUri(playbackUri)
            .setMediaId("watch-url")
            .setRequestMetadata(prepared.toRequestMetadata(scope = scope))
            .build()

        val source = requireNotNull(mediaItem.reusableSabrSource(requestedKey))

        assertEquals(playbackUri, source.url)
        assertEquals(acceptedKey, source.sourceKey)
        assertEquals(requestedKey, source.sabrRequestKey)
        assertEquals(prepared.sabrBinding, source.sabrBinding)
        assertEquals(prepared.sabrTarget, source.sabrTarget)
        assertEquals(prepared.sabrBinding, mediaItem.requireSabrTransportScope(scope))
        assertEquals(
            "session",
            mediaItem.requestMetadata.extras?.getString(MergedStreamMediaKeys.EXTRA_SABR_SESSION_ID),
        )
        assertEquals(
            3L,
            mediaItem.requestMetadata.extras?.getLong(MergedStreamMediaKeys.EXTRA_SABR_GENERATION),
        )
        assertEquals(
            "en.0",
            mediaItem.requestMetadata.extras?.getString(MergedStreamMediaKeys.EXTRA_SABR_AUDIO_TRACK_ID),
        )
        assertEquals(
            scope.serverId,
            mediaItem.requestMetadata.extras?.getString(MergedStreamMediaKeys.EXTRA_SERVER_ID),
        )
        assertEquals(
            scope.accountId,
            mediaItem.requestMetadata.extras?.getString(MergedStreamMediaKeys.EXTRA_ACCOUNT_ID),
        )
        assertEquals(
            scope.baseUrl,
            mediaItem.requestMetadata.extras?.getString(MergedStreamMediaKeys.EXTRA_SERVER_BASE_URL),
        )

        val replacement = prepared.copy(
            url = "typetype-sabr://playback/fresh",
        )
        val stored = mediaItem.requestMetadata.extras
        assertFalse(
            samePlayableSource(
                currentUrl = mediaItem.localConfiguration?.uri?.toString(),
                currentSourceKey = stored?.getString(MergedStreamMediaKeys.EXTRA_SOURCE_KEY),
                currentAudioUrl = stored?.getString(MergedStreamMediaKeys.EXTRA_AUDIO_URL),
                currentSabrBinding = prepared.sabrBinding,
                currentSabrTarget = prepared.sabrTarget,
                requestedSource = replacement,
            ),
        )
        val sought = prepared.copy(sabrBinding = prepared.sabrBinding?.copy(generation = 4L))
        assertFalse(
            samePlayableSource(
                currentUrl = playbackUri,
                currentSourceKey = acceptedKey,
                currentAudioUrl = null,
                currentSabrBinding = prepared.sabrBinding,
                currentSabrTarget = prepared.sabrTarget,
                requestedSource = sought,
            ),
        )
    }

    @Test
    fun serviceSeekReplacesGenerationWithoutChangingTheInternalPlaybackUri() {
        val scope = StreamRequestScope("server", "account", "https://instance.example/api/")
        val target = target(scope)
        val playbackUri = "typetype-sabr://playback/session"
        val manifest = "https://instance.example/api/sabr/playback/session/manifest"
        val source = PlayableSource(
            url = playbackUri,
            mimeType = "application/x-typetype-sabr",
            sourceKey = "sabr:video:137:140:en.0",
            sabrRequestKey = "requested-tuple",
            sabrBinding = SabrPlaybackBinding("session", 3L, 137, 140, "en.0"),
            sabrTarget = target,
        )
        val current = MediaItem.Builder()
            .setUri(playbackUri)
            .setMediaId("watch-url")
            .setRequestMetadata(source.toRequestMetadata(scope))
            .build()
        val replacement = current.withSabrPlayback(
            SabrPlaybackSession("session", manifest, 4L, 137, 140, "en.0"),
            target,
        )

        assertFalse(current.requestMetadata.extras?.getBoolean(
            MergedStreamMediaKeys.EXTRA_SABR_SESSION_CONTINUATION,
        ) == true)
        assertTrue(replacement.requestMetadata.extras?.getBoolean(
            MergedStreamMediaKeys.EXTRA_SABR_SESSION_CONTINUATION,
        ) == true)
        assertEquals(playbackUri, replacement.localConfiguration?.uri?.toString())
        assertEquals("requested-tuple", replacement.requestMetadata.extras?.getString(
            MergedStreamMediaKeys.EXTRA_SABR_REQUEST_KEY,
        ))
        assertEquals(4L, replacement.sabrPlaybackSeekState()?.binding?.generation)
        assertEquals(target, replacement.sabrPlaybackSeekState()?.target)
        assertFalse(current.sabrPlaybackSeekState() == replacement.sabrPlaybackSeekState())
    }

    @Test
    fun replacementSessionPreservesStreamMetadataSubtitleConfigurations() {
        val scope = StreamRequestScope("server", "account", "https://instance.example/api/")
        val target = target(scope)
        val subtitle = subtitle("en", "English", false).copy(
            trackId = "en-manual",
        )
        val current = MediaItem.Builder()
            .setUri("https://instance.example/api/sabr/playback/old/manifest")
            .setMediaId("watch-url")
            .setSubtitleConfigurations(listOf(subtitle).toSubtitleConfigurations())
            .build()

        val replacement = current.withSabrPlayback(
            SabrPlaybackSession(
                sessionId = "new",
                manifestUrl = "https://instance.example/api/sabr/playback/new/manifest",
                generation = 0L,
                videoItag = 137,
                audioItag = 140,
                audioTrackId = "en.0",
            ),
            target,
        )

        assertEquals(
            listOf(subtitle.url),
            replacement.localConfiguration?.subtitleConfigurations?.map { it.uri.toString() },
        )
    }

    @Test
    fun playbackTransportUsesTheStoredServerScopeInsteadOfTheInternalUri() {
        val scope = StreamRequestScope("server", "account", "https://instance.example/api/")
        val prepared = PlayableSource(
            url = "typetype-sabr://playback/session",
            mimeType = "application/x-typetype-sabr",
            sourceKey = "sabr:video:137:140:en.0",
            sabrRequestKey = "sabr:video:137:140:en.0",
            sabrBinding = SabrPlaybackBinding("session", 0L, 137, 140),
            sabrTarget = target(scope, audioTrackId = null),
        )
        val item = MediaItem.Builder()
            .setUri(prepared.url)
            .setRequestMetadata(prepared.toRequestMetadata(scope = scope))
            .build()

        assertEquals(prepared.sabrBinding, item.requireSabrTransportScope(scope))
    }

    @Test
    fun playbackMetadataKeepsTheAudioOnlySelectionPolicyWithItsAccountScope() {
        val scope = StreamRequestScope("server", "account", "https://instance.example/api/")
        val item = MediaItem.Builder()
            .setUri("https://instance.example/api/media/video")
            .setRequestMetadata(
                PlayableSource("https://instance.example/api/media/video", "video/mp4")
                    .toRequestMetadata(
                        scope = scope,
                        preferOriginalAudio = true,
                        preferredAudioLocale = "fr",
                    ),
            )
            .build()
        val extras = requireNotNull(item.requestMetadata.extras)

        assertEquals(scope, extras.streamRequestScope())
        assertTrue(extras.getBoolean(MergedStreamMediaKeys.EXTRA_AUDIO_ONLY_PREFER_ORIGINAL))
        assertEquals(
            "fr",
            extras.getString(MergedStreamMediaKeys.EXTRA_AUDIO_ONLY_PREFERRED_LOCALE),
        )
    }

    private fun target(
        scope: StreamRequestScope,
        videoItag: Int = 137,
        audioTrackId: String? = "en.0",
    ) = SabrPlaybackTarget(
        videoId = "video",
        requestScope = scope,
        videoItag = videoItag,
        audioItag = 140,
        audioTrackId = audioTrackId,
        recoveryVideoItags = setOf(136, 135).filterTo(linkedSetOf()) { it != videoItag },
    )

    private fun subtitle(
        language: String,
        label: String,
        autoGenerated: Boolean,
    ) = StreamSubtitleSource(
        url = "https://instance.example/api/subtitles/$language/$autoGenerated.vtt",
        mimeType = "text/vtt",
        languageTag = language,
        displayLanguageName = label,
        isAutoGenerated = autoGenerated,
    )
}
