package dev.typetype.android.feature.player

import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.MimeTypes
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.media3.common.text.CueGroup
import androidx.media3.common.util.UnstableApi
import androidx.media3.exoplayer.ExoPlayer
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.services.toSubtitleConfigurations
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicReference
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@UnstableApi
@RunWith(AndroidJUnit4::class)
class SubtitlePlaybackDeviceTest {
    private lateinit var player: ExoPlayer
    private lateinit var audioFile: File
    private lateinit var subtitleFile: File

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        audioFile = File.createTempFile("subtitle-playback", ".wav", context.cacheDir)
        subtitleFile = File.createTempFile("subtitle-playback", ".ttml", context.cacheDir)
        audioFile.writeBytes(silentWaveFixture())
        subtitleFile.writeText(
            """
            <tt xmlns="http://www.w3.org/ns/ttml">
              <body><div><p begin="00:00:00.000" end="00:00:19.000">Subtitle playback works</p></div></body>
            </tt>
            """.trimIndent(),
        )
        onMain {
            player = ExoPlayer.Builder(context).build()
            player.trackSelectionParameters = player.trackSelectionParameters.buildUpon()
                .setTrackTypeDisabled(C.TRACK_TYPE_TEXT, true)
                .build()
        }
    }

    @After
    fun tearDown() {
        onMain { player.release() }
        audioFile.delete()
        subtitleFile.delete()
    }

    @Test
    fun media3LoadsAndRendersAttachedTtmlTrack() {
        val renderedCue = AtomicReference<String?>()
        val playbackError = AtomicReference<PlaybackException?>()
        val observedTracks = AtomicReference<List<String>>(emptyList())
        val cueReady = CountDownLatch(1)
        val subtitle = StreamSubtitleSource(
            url = subtitleFile.toURI().toString(),
            mimeType = MimeTypes.APPLICATION_TTML,
            languageTag = "en",
            displayLanguageName = "English",
            isAutoGenerated = false,
            trackId = "caption-en",
        )
        onMain {
            player.addListener(
                object : Player.Listener {
                    override fun onTracksChanged(tracks: androidx.media3.common.Tracks) {
                        observedTracks.set(
                            tracks.describe(),
                        )
                    }

                    override fun onCues(cueGroup: CueGroup) {
                        val text = cueGroup.cues.firstOrNull()?.text?.toString()
                        if (text != null) {
                            renderedCue.set(text)
                            cueReady.countDown()
                        }
                    }

                    override fun onPlayerError(error: PlaybackException) {
                        playbackError.set(error)
                        cueReady.countDown()
                    }
                },
            )
            player.setMediaItem(
                MediaItem.Builder()
                    .setUri(audioFile.toURI().toString())
                    .setSubtitleConfigurations(listOf(subtitle).toSubtitleConfigurations())
                    .build(),
            )
            player.prepare()
            player.play()
        }

        assertTrue(
            "No tracks became available",
            waitUntil { onMain { player.currentTracks.groups.isNotEmpty() } },
        )
        onMain {
            observedTracks.set(player.currentTracks.describe())
            player.selectSubtitleTrack("caption-en", player.currentTracks)
        }
        assertTrue(
            "No cue rendered from tracks ${onMain { player.currentTracks.describe() }}, " +
                "parameters ${onMain { player.trackSelectionParameters.describe() }}",
            cueReady.await(5, TimeUnit.SECONDS),
        )
        assertNull(playbackError.get())
        assertEquals("Subtitle playback works", renderedCue.get())
    }

    private fun androidx.media3.common.Tracks.describe(): List<String> =
        groups.flatMap { group ->
            List(group.length) { index ->
                val format = group.getTrackFormat(index)
                listOf(
                    group.type,
                    format.id,
                    format.language,
                    format.label,
                    format.sampleMimeType,
                    group.isTrackSelected(index).toString(),
                ).joinToString("|")
            }
        }

    private fun androidx.media3.common.TrackSelectionParameters.describe(): String =
        "disabled=$disabledTrackTypes overrides=" +
            overrides.values.joinToString { "${it.mediaTrackGroup.id}:${it.trackIndices}" }

    private fun waitUntil(
        timeoutMillis: Long = 5_000L,
        condition: () -> Boolean,
    ): Boolean {
        val deadline = System.nanoTime() + TimeUnit.MILLISECONDS.toNanos(timeoutMillis)
        while (System.nanoTime() < deadline) {
            if (condition()) return true
            Thread.sleep(20L)
        }
        return condition()
    }

    private fun <T> onMain(block: () -> T): T {
        val result = AtomicReference<Result<T>>()
        InstrumentationRegistry.getInstrumentation().runOnMainSync {
            result.set(runCatching(block))
        }
        return result.get().getOrThrow()
    }
}
