package dev.typetype.android.feature.player.components

import androidx.activity.ComponentActivity
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.test.assertCountEquals
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.v2.createAndroidComposeRule
import androidx.compose.ui.test.onAllNodesWithText
import androidx.compose.ui.test.onNodeWithText
import androidx.media3.common.text.Cue
import androidx.media3.common.util.UnstableApi
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.extractor.text.CuesWithTiming
import dev.typetype.android.domain.stream.StreamSubtitleSource
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test

@UnstableApi
class PlayerSubtitleOverlayTest {
    @get:Rule
    val composeRule = createAndroidComposeRule<ComponentActivity>()

    private lateinit var player: ExoPlayer
    private val selectedSource = mutableStateOf(subtitle("manual"))

    @Before
    fun setUp() {
        composeRule.runOnIdle {
            player = ExoPlayer.Builder(composeRule.activity).build()
        }
    }

    @After
    fun tearDown() {
        composeRule.runOnIdle { player.release() }
    }

    @Test
    fun selectedServerSubtitleIsDisplayedAndSwitchesTracks() {
        composeRule.setContent {
            MaterialTheme {
                PlayerSubtitleOverlay(
                    player = player,
                    controlsVisible = false,
                    subtitlesVisible = true,
                    externalSource = selectedSource.value,
                    loadExternalCues = { source ->
                        Result.success(listOf(cueFor(source.trackId.orEmpty())))
                    },
                )
            }
        }

        composeRule.onNodeWithText("Manual subtitle").assertIsDisplayed()

        composeRule.runOnIdle { selectedSource.value = subtitle("auto") }

        composeRule.onNodeWithText("Automatic subtitle").assertIsDisplayed()
        composeRule.onAllNodesWithText("Manual subtitle").assertCountEquals(0)
    }

    private fun cueFor(trackId: String): CuesWithTiming = CuesWithTiming(
        listOf(Cue.Builder().setText("${trackId.displayName()} subtitle").build()),
        0L,
        10_000_000L,
    )

    private fun subtitle(trackId: String) = StreamSubtitleSource(
        url = "https://instance.example/api/subtitles/youtube/video-id" +
            "?language=en&variant=$trackId&format=ttml",
        mimeType = "application/ttml+xml",
        languageTag = "en",
        displayLanguageName = "English",
        isAutoGenerated = trackId == "auto",
        trackId = trackId,
    )

    private fun String.displayName(): String = when (this) {
        "auto" -> "Automatic"
        else -> replaceFirstChar { character -> character.uppercase() }
    }
}
