package dev.typetype.android.domain.stream

import java.nio.charset.StandardCharsets
import java.security.MessageDigest

internal fun List<StreamSubtitleSource>.sabrSubtitleCatalogFingerprint(): String {
    val digest = MessageDigest.getInstance("SHA-256")
    forEach { subtitle ->
        listOf(
            subtitle.trackId.orEmpty(),
            subtitle.url,
            subtitle.mimeType,
            subtitle.languageTag,
            subtitle.displayLanguageName,
            subtitle.isAutoGenerated.toString(),
        ).forEach { value ->
            digest.update(value.toByteArray(StandardCharsets.UTF_8))
            digest.update(FIELD_SEPARATOR)
        }
        digest.update(RECORD_SEPARATOR)
    }
    return digest.digest().joinToString("") { byte ->
        val value = byte.toInt() and 0xff
        "${HEX_DIGITS[value ushr 4]}${HEX_DIGITS[value and 0x0f]}"
    }
}

private val FIELD_SEPARATOR = byteArrayOf(0)
private val RECORD_SEPARATOR = byteArrayOf(1)
private const val HEX_DIGITS = "0123456789abcdef"
