package dev.typetype.android.domain.stream

import dev.typetype.android.domain.feed.Video

data class Stream(
    val id: String,
    val title: String,
    val uploaderName: String,
    val uploaderAvatarUrl: String,
    val uploaderUrl: String,
    val uploaderSubscriberCount: Long,
    val uploaderVerified: Boolean,
    val thumbnailUrl: String,
    val description: String,
    val durationSeconds: Long,
    val viewCount: Long,
    val likeCount: Long,
    val dislikeCount: Long,
    val uploadedAtMillis: Long,
    val hlsUrl: String?,
    val dashMpdUrl: String?,
    val progressiveUrl: String?,
    val serverDashManifestUrl: String?,
    val serverHlsManifestUrl: String?,
    val muxedVideoStreams: List<StreamVideoSource> = emptyList(),
    val videoOnlyStreams: List<StreamVideoSource> = emptyList(),
    val audioStreams: List<StreamAudioSource> = emptyList(),
    val subtitles: List<StreamSubtitleSource> = emptyList(),
    val startPositionMillis: Long,
    val sponsorBlockSegments: List<SponsorBlockSegment> = emptyList(),
    val chapters: List<Chapter> = emptyList(),
    val relatedStreams: List<Video> = emptyList(),
)

data class StreamVideoSource(
    val url: String,
    val mimeType: String,
    val resolution: String,
    val width: Int,
    val height: Int,
    val fps: Int,
    val bitrate: Int?,
    val isVideoOnly: Boolean,
)

data class StreamAudioSource(
    val url: String,
    val mimeType: String,
    val bitrate: Int?,
    val quality: String?,
    val audioTrackId: String?,
    val audioTrackName: String?,
    val audioLocale: String?,
    val isOriginal: Boolean,
)

data class StreamSubtitleSource(
    val url: String,
    val mimeType: String,
    val languageTag: String,
    val displayLanguageName: String,
    val isAutoGenerated: Boolean,
)
