package dev.typetype.android.domain.stream

import dev.typetype.android.domain.feed.Video

data class Stream(
    val playbackContract: StreamPlaybackContract,
    val id: String,
    val title: String,
    val uploaderName: String,
    val uploaderAvatarUrl: String,
    val uploaderUrl: String,
    val uploaderSubscriberCount: Long,
    val uploaderVerified: Boolean,
    val thumbnailUrl: String,
    val description: String,
    val durationSeconds: Long,
    val viewCount: Long,
    val likeCount: Long,
    val dislikeCount: Long,
    val uploadedAtMillis: Long,
    val hlsUrl: String?,
    val dashMpdUrl: String?,
    val progressiveUrl: String?,
    val serverDashManifestUrl: String?,
    val serverHlsManifestUrl: String?,
    val serverSabrManifestUrl: String? = null,
    val sabrVideoStreams: List<StreamVideoSource> = emptyList(),
    val sabrAudioStreams: List<StreamAudioSource> = emptyList(),
    val requestScope: StreamRequestScope? = null,
    val muxedVideoStreams: List<StreamVideoSource> = emptyList(),
    val videoOnlyStreams: List<StreamVideoSource> = emptyList(),
    val audioStreams: List<StreamAudioSource> = emptyList(),
    val originalAudioTrackId: String? = null,
    val preferredDefaultAudioTrackId: String? = null,
    val subtitles: List<StreamSubtitleSource> = emptyList(),
    val storyboard: StreamStoryboard? = null,
    val startPositionMillis: Long,
    val sponsorBlockSegments: List<SponsorBlockSegment> = emptyList(),
    val chapters: List<Chapter> = emptyList(),
    val relatedStreams: List<Video> = emptyList(),
    val isLive: Boolean = false,
    val isPostLive: Boolean = false,
    val isLiveContent: Boolean = false,
    val category: String? = null,
)

data class StreamStoryboard(
    val urls: List<String>,
    val frameWidth: Int,
    val frameHeight: Int,
    val totalCount: Int,
    val durationPerFrameMillis: Long,
    val framesPerPageX: Int,
    val framesPerPageY: Int,
) {
    fun frameAt(positionMs: Long): StreamStoryboardFrame? {
        val totalFrames = totalCount.takeIf { it > 0 } ?: return null
        val duration = durationPerFrameMillis.takeIf { it > 0L } ?: return null
        val pageColumns = framesPerPageX.takeIf { it > 0 } ?: return null
        val pageRows = framesPerPageY.takeIf { it > 0 } ?: return null
        if (frameWidth <= 0 || frameHeight <= 0 || urls.isEmpty()) return null

        val elapsedFrames = positionMs / duration
        val frameIndex = when {
            elapsedFrames <= 0L -> 0
            elapsedFrames >= totalFrames - 1L -> totalFrames - 1
            else -> elapsedFrames.toInt()
        }
        val framesPerPage = pageColumns * pageRows
        val pageIndex = (frameIndex / framesPerPage).coerceIn(0, urls.lastIndex)
        val pageFrameIndex = frameIndex % framesPerPage
        val url = urls.getOrNull(pageIndex) ?: return null
        return StreamStoryboardFrame(
            url = url,
            x = (pageFrameIndex % pageColumns) * frameWidth,
            y = (pageFrameIndex / pageColumns) * frameHeight,
            width = frameWidth,
            height = frameHeight,
        )
    }
}

data class StreamStoryboardFrame(
    val url: String,
    val x: Int,
    val y: Int,
    val width: Int,
    val height: Int,
)

enum class StreamPlaybackContract {
    ServerSabr,
    ProviderMedia,
}

data class StreamVideoSource(
    val url: String,
    val mimeType: String,
    val codec: String?,
    val resolution: String,
    val width: Int,
    val height: Int,
    val fps: Int,
    val bitrate: Int?,
    val isVideoOnly: Boolean,
    val itag: Int = 0,
)

data class StreamAudioSource(
    val url: String,
    val mimeType: String,
    val codec: String?,
    val bitrate: Int?,
    val quality: String?,
    val audioTrackId: String?,
    val audioTrackName: String?,
    val audioLocale: String?,
    val isOriginal: Boolean,
    val itag: Int = 0,
)

data class StreamRequestScope(
    val serverId: String,
    val accountId: String,
    val baseUrl: String,
)

data class StreamSubtitleSource(
    val url: String,
    val mimeType: String,
    val languageTag: String,
    val displayLanguageName: String,
    val isAutoGenerated: Boolean,
    val trackId: String? = null,
)
