package dev.typetype.android.services

import androidx.core.net.toUri
import androidx.media3.common.MediaItem
import androidx.media3.common.MimeTypes
import dev.typetype.android.domain.stream.StreamSubtitleSource

internal fun List<StreamSubtitleSource>.toSubtitleConfigurations():
    List<MediaItem.SubtitleConfiguration> =
    distinctBy(StreamSubtitleSource::key).map { source ->
        MediaItem.SubtitleConfiguration.Builder(source.url.toUri())
            .setId(source.key)
            .setMimeType(source.mimeType.ifBlank { MimeTypes.TEXT_VTT })
            .setLanguage(source.languageTag.takeIf(String::isNotBlank))
            .setLabel(source.displayLanguageName)
            .setSelectionFlags(0)
            .build()
    }

private val StreamSubtitleSource.key: String
    get() = trackId?.takeIf(String::isNotBlank)
        ?: languageTag.takeIf(String::isNotBlank)
            ?.let { "$it:$isAutoGenerated" }
        ?: url
