package video.typetype.tv.ui

import androidx.compose.runtime.Composable
import video.typetype.sdk.core.Comment
import video.typetype.sdk.core.Video
import video.typetype.tv.data.TvAppState

@Composable
internal fun ActivePlayer(
    state: TvAppState,
    commentsState: CommentsUiState,
    onClose: () -> Unit,
    onPlayNext: () -> Unit,
    onPlayQueueItem: (Video) -> Unit,
    onSelectVideoTrack: (Int, Long) -> Unit,
    onSelectAudioTrack: (Int, String?, Long) -> Unit,
    onSelectSubtitle: (String?, Boolean, String?, Long) -> Unit,
    onLoadMoreComments: () -> Unit,
    onLoadCommentReplies: (Comment) -> Unit,
) {
    val video = state.selectedVideo ?: return
    val stream = state.stream ?: return
    val playback = state.playback ?: return
    PlayerScreen(
        video = video,
        stream = stream,
        playback = playback,
        audioOnly = state.audioOnlyStream,
        supportedVideoItags = state.supportedVideoItags,
        subtitle = playback.subtitles.firstOrNull {
            it.languageTag == state.selectedSubtitleLanguage &&
                it.isAutoGenerated == state.selectedSubtitleAuto &&
                it.name == state.selectedSubtitleName
        },
        commentsState = commentsState,
        settings = state.settings,
        onClose = onClose,
        onPlayNext = onPlayNext,
        onPlayQueueItem = onPlayQueueItem,
        onSelectVideoTrack = onSelectVideoTrack,
        onSelectAudioTrack = onSelectAudioTrack,
        onSelectSubtitle = onSelectSubtitle,
        onLoadMoreComments = onLoadMoreComments,
        onLoadCommentReplies = onLoadCommentReplies,
        isAdvancing = state.isAdvancingPlayback,
        serverError = state.errorMessage,
    )
}
