package video.typetype.tv.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.tv.material3.Button
import androidx.tv.material3.MaterialTheme
import androidx.tv.material3.Surface
import androidx.tv.material3.Text
import video.typetype.sdk.core.PlaybackSession
import video.typetype.sdk.core.StreamDetails
import video.typetype.sdk.core.SubtitleTrack
import video.typetype.sdk.core.isSabrPlaybackTrack

@Composable
internal fun PlaybackTrackPanel(
    stream: StreamDetails,
    playback: PlaybackSession,
    supportedVideoItags: Set<Int>,
    selectedVideoItag: Int?,
    selectedAudioItag: Int?,
    selectedAudioTrackId: String?,
    subtitle: SubtitleTrack?,
    onVideoTrack: (Int) -> Unit,
    onAudioTrack: (Int, String?) -> Unit,
    onSubtitle: (String?, Boolean, String?) -> Unit,
    onDismiss: () -> Unit,
) {
    val videos = stream.videoOnlyStreams.filter {
        it.isSabrPlaybackTrack() && it.itag in supportedVideoItags
    }.distinctBy { it.itag }
    val audios = stream.audioStreams.filter { it.isSabrPlaybackTrack() }.distinctBy { it.itag to it.audioTrackId }
    val initialVideoIndex = videos.indexOfFirst { it.itag == selectedVideoItag }.coerceAtLeast(0)
    val initialFocus = remember(videos, selectedVideoItag) { FocusRequester() }
    LaunchedEffect(videos, selectedVideoItag) {
        if (videos.isNotEmpty()) initialFocus.requestFocus()
    }
    Surface(
        modifier = Modifier.width(620.dp),
        shape = RoundedCornerShape(18.dp),
        colors = androidx.tv.material3.SurfaceDefaults.colors(
            containerColor = Color(0xFA111318),
            contentColor = Color.White,
        ),
    ) {
        LazyColumn(
            modifier = Modifier.heightIn(max = 760.dp).padding(24.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            item { Text("Playback options", color = Color.White, style = MaterialTheme.typography.headlineSmall) }
            item { Text("Video quality", color = Color(0xFF8AB4F8), style = MaterialTheme.typography.labelLarge) }
            itemsIndexed(videos) { index, video ->
                Button(
                    onClick = { onVideoTrack(video.itag) },
                    modifier = if (index == initialVideoIndex) Modifier.focusRequester(initialFocus) else Modifier,
                ) {
                    Text(trackLabel(video.resolution, video.codec, video.frameRate.takeIf { it > 0 }?.let { "$it fps" }, video.itag == selectedVideoItag))
                }
            }
            item { Text("Audio", color = Color(0xFF8AB4F8), style = MaterialTheme.typography.labelLarge) }
            items(audios) { audio ->
                Button(onClick = { onAudioTrack(audio.itag, audio.audioTrackId) }) {
                    val detail = buildString {
                        playbackCodecLabel(audio.codec)?.let { append(it) }
                        audio.bitrate?.takeIf { it > 0L }?.let {
                            if (isNotEmpty()) append(" · ")
                            append(playbackBitrateLabel(it))
                        }
                    }.takeIf(String::isNotEmpty)
                    Text(trackLabel(audio.audioTrackName ?: audio.audioLocale ?: "Audio", null, detail, audio.itag == selectedAudioItag && audio.audioTrackId == selectedAudioTrackId))
                }
            }
            item { Text("Subtitles", color = Color(0xFF8AB4F8), style = MaterialTheme.typography.labelLarge) }
            item {
                Button(onClick = { onSubtitle(null, false, null) }) {
                    Text(if (subtitle == null) "Off · selected" else "Off")
                }
            }
            items(playback.subtitles.distinctBy { Triple(it.languageTag, it.isAutoGenerated, it.name) }) { track ->
                Button(onClick = { onSubtitle(track.languageTag, track.isAutoGenerated, track.name) }) {
                    val kind = if (track.isAutoGenerated) "automatic" else "manual"
                    val selected = subtitle?.languageTag == track.languageTag &&
                        subtitle.isAutoGenerated == track.isAutoGenerated && subtitle.name == track.name
                    Text("${track.displayName ?: track.languageTag} · $kind${if (selected) " · selected" else ""}")
                }
            }
            item { Button(onClick = onDismiss) { Text("Close") } }
        }
    }
}

private fun trackLabel(name: String, codec: String?, detail: String?, selected: Boolean): String = buildString {
    append(name)
    playbackCodecLabel(codec)?.let { append(" · ").append(it) }
    detail?.let { append(" · ").append(it) }
    if (selected) append(" · selected")
}
