@file:androidx.annotation.OptIn(markerClass = [androidx.media3.common.util.UnstableApi::class])

package video.typetype.tv.ui

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.setValue
import androidx.core.content.ContextCompat
import androidx.media3.common.C
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.media3.session.MediaController
import kotlinx.coroutines.delay
import video.typetype.sdk.core.AudioOnlyStream
import video.typetype.sdk.core.PlaybackSession
import video.typetype.sdk.core.StreamDetails
import video.typetype.sdk.core.SubtitleTrack
import video.typetype.sdk.core.UserSettings
import video.typetype.sdk.core.Video
import video.typetype.tv.player.SUBTITLE_ERROR_EXTRA
import video.typetype.tv.player.PLAYBACK_ERROR_EXTRA
import video.typetype.tv.player.TypeTypePlaybackService

internal class PlayerSessionBinding {
    var controller: MediaController? by mutableStateOf(null)
        private set
    var playbackError: String? by mutableStateOf(null)
        private set
    var subtitleError: String? by mutableStateOf(null)
        private set
    var positionMilliseconds: Long by mutableLongStateOf(0L)
        private set
    var durationMilliseconds: Long by mutableLongStateOf(0L)
        private set
    var isPlaying: Boolean by mutableStateOf(false)
        private set
    var playbackFailed: Boolean = false
        private set

    fun attach(value: MediaController) {
        controller = value
        isPlaying = value.isPlaying
    }

    fun onPlayerError(error: PlaybackException) {
        playbackFailed = true
        playbackError = (error.cause?.message ?: error.message.orEmpty()).userMessage()
    }

    fun onPlaybackReady() {
        playbackFailed = false
        playbackError = null
    }

    fun onIsPlayingChanged(value: Boolean) {
        isPlaying = value
    }

    fun refresh() {
        val player = controller
        val duration = player?.duration ?: C.TIME_UNSET
        positionMilliseconds = player?.currentPosition?.coerceAtLeast(0L) ?: 0L
        durationMilliseconds = duration.coerceAtLeast(0L)
        subtitleError = player?.sessionExtras?.getString(SUBTITLE_ERROR_EXTRA)
        player?.sessionExtras?.getString(PLAYBACK_ERROR_EXTRA)?.let { playbackError = it.userMessage() }
    }

    fun detach(listener: Player.Listener) {
        controller?.removeListener(listener)
        controller?.release()
        controller = null
    }
}

private fun String.userMessage(): String = when {
    contains("throttled", ignoreCase = true) ->
        "The server is temporarily throttling playback."
    contains("SABR", ignoreCase = true) ||
        contains("Invalid integer size", ignoreCase = true) ->
        "The server returned an invalid media segment."
    else -> ifBlank { "Playback could not be started." }
}

@Composable
internal fun rememberPlayerSessionBinding(
    context: Context,
    video: Video,
    stream: StreamDetails,
    playback: PlaybackSession,
    subtitle: SubtitleTrack?,
    audioOnly: AudioOnlyStream?,
    settings: UserSettings,
    onEnded: () -> Unit,
): PlayerSessionBinding {
    val state = remember(playback.sessionId) { PlayerSessionBinding() }
    val latestEnded by rememberUpdatedState(onEnded)
    val controllerFuture = remember(
        playback.sessionId,
        playback.selectedVideoItag,
        playback.selectedAudioItag,
        playback.audioTrackId,
        stream.id,
        subtitle?.languageTag,
        subtitle?.isAutoGenerated,
        subtitle?.name,
        audioOnly?.sourceUrl,
        settings,
    ) {
        if (TypeTypePlaybackService.play(context, video, stream, playback, subtitle, audioOnly, settings)) {
            TypeTypePlaybackService.controller(context)
        } else null
    }
    DisposableEffect(controllerFuture) {
        val listener = object : Player.Listener {
            override fun onPlayerError(error: PlaybackException) = state.onPlayerError(error)

            override fun onPlaybackStateChanged(playbackState: Int) {
                if (playbackState == Player.STATE_READY) state.onPlaybackReady()
                if (playbackState == Player.STATE_ENDED && !state.playbackFailed) latestEnded()
            }

            override fun onIsPlayingChanged(isPlaying: Boolean) = state.onIsPlayingChanged(isPlaying)
        }
        controllerFuture?.addListener(
            {
                runCatching { controllerFuture.get() }.getOrNull()?.let { controller ->
                    controller.addListener(listener)
                    state.attach(controller)
                }
            },
            ContextCompat.getMainExecutor(context),
        )
        onDispose { state.detach(listener) }
    }
    LaunchedEffect(state.controller) {
        while (true) {
            state.refresh()
            delay(500L)
        }
    }
    return state
}
