package dev.typetype.android.data.stream

import dev.typetype.android.data.network.dto.SubtitleItem
import dev.typetype.android.domain.stream.StreamSubtitleSource
import okhttp3.HttpUrl
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull

internal fun SubtitleItem.toClientSubtitleSource(index: Int): StreamSubtitleSource? {
    val source = url.trim().toHttpUrlOrNull() ?: return null
    val language = languageTag.trim()
    val automatic = isAutoGenerated || source.isAutomaticCaption()
    val youtubeTimedText = source.isYoutubeTimedText()
    val playbackUrl = if (youtubeTimedText) {
        source.newBuilder().setQueryParameter("fmt", "vtt").build()
    } else {
        source
    }
    return StreamSubtitleSource(
        url = playbackUrl.toString(),
        mimeType = if (youtubeTimedText) WEBVTT_MIME_TYPE else mimeType.trim(),
        languageTag = language,
        displayLanguageName = displayLanguageName.trim(),
        isAutoGenerated = automatic,
        trackId = source.stableTrackId(index, language, automatic),
    )
}

private fun HttpUrl.isYoutubeTimedText(): Boolean =
    (host == YOUTUBE_HOST || host.endsWith(".$YOUTUBE_HOST")) &&
        encodedPath == YOUTUBE_TIMED_TEXT_PATH

private fun HttpUrl.isAutomaticCaption(): Boolean =
    queryParameter("kind") == "asr" || queryParameter("vssId")?.startsWith("a.") == true

private fun HttpUrl.stableTrackId(index: Int, language: String, automatic: Boolean): String =
    listOfNotNull(
        "subtitle",
        index.toString(),
        language.ifBlank { "und" },
        if (automatic) "auto" else "manual",
        queryParameter("vssId")?.takeIf(String::isNotBlank),
        queryParameter("name")?.takeIf(String::isNotBlank),
        queryParameter("tlang")?.takeIf(String::isNotBlank),
    ).joinToString(":")

private const val WEBVTT_MIME_TYPE = "text/vtt"
private const val YOUTUBE_HOST = "youtube.com"
private const val YOUTUBE_TIMED_TEXT_PATH = "/api/timedtext"
