package dev.typetype.android.data.stream

import dev.typetype.android.data.network.dto.SubtitleItem
import dev.typetype.android.domain.stream.StreamSubtitleSource
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull

internal fun SubtitleItem.toYoutubeSubtitleSource(
    baseUrl: String,
    videoId: String,
): StreamSubtitleSource? {
    val normalizedVideoId = videoId.trim().takeIf(String::isNotEmpty) ?: return null
    val language = languageTag.trim().takeIf(String::isNotEmpty) ?: return null
    val source = url.toHttpUrlOrNull()
    val variant = if (
        isAutoGenerated ||
        source?.queryParameter("kind") == "asr" ||
        source?.queryParameter("vssId")?.startsWith("a.") == true
    ) {
        "auto"
    } else {
        "manual"
    }
    val endpoint = baseUrl.toHttpUrlOrNull()
        ?.newBuilder()
        ?.addPathSegment("subtitles")
        ?.addPathSegment("youtube")
        ?.addPathSegment(normalizedVideoId)
        ?.addQueryParameter("language", language)
        ?.addQueryParameter("variant", variant)
        ?.addQueryParameter("format", "ttml")
        ?.apply {
            source?.queryParameter("lang")
                ?.takeIf(String::isNotBlank)
                ?.let { addQueryParameter("sourceLanguage", it) }
            source?.queryParameter("tlang")
                ?.takeIf(String::isNotBlank)
                ?.let { addQueryParameter("translation", it) }
            source?.queryParameter("name")
                ?.takeIf(String::isNotBlank)
                ?.let { addQueryParameter("name", it) }
        }
        ?.build()
        ?.toString()
        ?: return null
    return StreamSubtitleSource(
        url = endpoint,
        mimeType = TTML_MIME_TYPE,
        languageTag = language,
        displayLanguageName = displayLanguageName,
        isAutoGenerated = variant == "auto",
        trackId = endpoint,
    )
}

private const val TTML_MIME_TYPE = "application/ttml+xml"
