package dev.typetype.android.data.stream

import dev.typetype.android.data.network.dto.SubtitleItem
import okhttp3.HttpUrl.Companion.toHttpUrl
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class ClientSubtitleSourceTest {
    @Test
    fun `YouTube timed text stays client side and requests WebVTT`() {
        val source = subtitle(
            url = "https://www.youtube.com/api/timedtext?v=video&lang=en&name=CC1&sig=secret",
            language = "en",
        ).toClientSubtitleSource(index = 0)
        val endpoint = requireNotNull(source).url.toHttpUrl()

        assertEquals("www.youtube.com", endpoint.host)
        assertEquals("/api/timedtext", endpoint.encodedPath)
        assertEquals("vtt", endpoint.queryParameter("fmt"))
        assertEquals("secret", endpoint.queryParameter("sig"))
        assertEquals("text/vtt", source.mimeType)
        assertFalse(source.url.contains("/subtitles/youtube/"))
    }

    @Test
    fun `translated automatic track preserves signed identifiers`() {
        val source = subtitle(
            url = "https://m.youtube.com/api/timedtext?lang=en&tlang=fr&kind=asr&vssId=a.en",
            language = "fr",
        ).toClientSubtitleSource(index = 2)
        val endpoint = requireNotNull(source).url.toHttpUrl()

        assertTrue(source.isAutoGenerated)
        assertEquals("en", endpoint.queryParameter("lang"))
        assertEquals("fr", endpoint.queryParameter("tlang"))
        assertEquals("asr", endpoint.queryParameter("kind"))
        assertTrue(source.trackId.orEmpty().contains("a.en"))
    }

    @Test
    fun `non YouTube tracks remain direct and retain their format`() {
        val source = subtitle(
            url = "https://captions.example/video/en.ttml",
            language = "en",
            mimeType = "application/ttml+xml",
        ).toClientSubtitleSource(index = 1)

        assertEquals("https://captions.example/video/en.ttml", requireNotNull(source).url)
        assertEquals("application/ttml+xml", source.mimeType)
    }

    @Test
    fun `invalid URL is not exposed to playback`() {
        assertNull(subtitle(url = "expired signed URL").toClientSubtitleSource(index = 0))
    }

    private fun subtitle(
        url: String,
        language: String = "en",
        mimeType: String = "text/xml",
    ) = SubtitleItem(
        url = url,
        mimeType = mimeType,
        languageTag = language,
        displayLanguageName = language,
        isAutoGenerated = false,
    )
}
