package dev.typetype.android.data.stream

import dev.typetype.android.data.account.AccountScope
import dev.typetype.android.data.account.AccountScopeProvider
import dev.typetype.android.domain.stream.StreamSubtitleSource
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.runBlocking
import okhttp3.Cookie
import okhttp3.CookieJar
import okhttp3.HttpUrl
import okhttp3.OkHttpClient
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

class RemoteSubtitleRepositoryTest {
    private lateinit var server: MockWebServer
    private lateinit var scope: FakeAccountScopeProvider

    @Before
    fun setUp() {
        server = MockWebServer()
        server.start()
        scope = FakeAccountScopeProvider()
    }

    @After
    fun tearDown() {
        server.shutdown()
    }

    @Test
    fun `loads direct captions without account credentials or cookies`() = runBlocking {
        server.enqueue(MockResponse().setBody("WEBVTT\n\n00:00.000 --> 00:01.000\nHello"))
        val baseClient = OkHttpClient.Builder()
            .cookieJar(SecretCookieJar)
            .addInterceptor { chain ->
                chain.proceed(
                    chain.request().newBuilder()
                        .header("Authorization", "Bearer private-token")
                        .header("Proxy-Authorization", "private-proxy-token")
                        .build(),
                )
            }
            .build()
        val repository = RemoteSubtitleRepository(baseClient, scope)

        val bytes = repository.load(subtitle(server.url("/api/timedtext"))).getOrThrow()
        val request = server.takeRequest()

        assertTrue(bytes.decodeToString().startsWith("WEBVTT"))
        assertNull(request.getHeader("Authorization"))
        assertNull(request.getHeader("Proxy-Authorization"))
        assertNull(request.getHeader("Cookie"))
        assertEquals(1, scope.verifications)
    }

    @Test
    fun `rejects oversized captions before reading the response`() = runBlocking {
        server.enqueue(
            MockResponse()
                .setHeader("Content-Length", 5 * 1024 * 1024 + 1),
        )
        val repository = RemoteSubtitleRepository(OkHttpClient(), scope)

        val result = repository.load(subtitle(server.url("/captions")))

        assertTrue(result.isFailure)
    }

    @Test
    fun `discards captions when the active account changes`() = runBlocking {
        server.enqueue(MockResponse().setBody("WEBVTT"))
        scope.changeBeforeVerify = true
        val repository = RemoteSubtitleRepository(OkHttpClient(), scope)

        val result = repository.load(subtitle(server.url("/captions")))

        assertTrue(result.isFailure)
    }

    private fun subtitle(url: HttpUrl) = StreamSubtitleSource(
        url = url.toString(),
        mimeType = "text/vtt",
        languageTag = "en",
        displayLanguageName = "English",
        isAutoGenerated = false,
    )

    private class FakeAccountScopeProvider : AccountScopeProvider {
        private val current = MutableStateFlow(AccountScope("server", "account"))
        var changeBeforeVerify = false
        var verifications = 0

        override fun observe(): Flow<AccountScope?> = current

        override suspend fun require(): AccountScope = current.value

        override suspend fun verify(expected: AccountScope) {
            verifications += 1
            if (changeBeforeVerify) current.value = AccountScope("server", "other")
            check(current.value == expected)
        }
    }

    private object SecretCookieJar : CookieJar {
        override fun saveFromResponse(url: HttpUrl, cookies: List<Cookie>) = Unit

        override fun loadForRequest(url: HttpUrl): List<Cookie> = listOf(
            Cookie.Builder()
                .name("session")
                .value("private-cookie")
                .hostOnlyDomain(url.host)
                .build(),
        )
    }
}
