package dev.typetype.android.data.stream

import dev.typetype.android.data.network.dto.SubtitleItem
import okhttp3.HttpUrl.Companion.toHttpUrl
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class YoutubeSubtitleEndpointTest {
    @Test
    fun `manual track uses the server TTML endpoint`() {
        val source = subtitle(
            url = "https://youtube.example/timedtext?lang=en&name=English",
            language = "en",
        ).toYoutubeSubtitleSource(BASE_URL, VIDEO_ID)
        val endpoint = requireNotNull(source).url.toHttpUrl()

        assertEquals("/api/subtitles/youtube/$VIDEO_ID", endpoint.encodedPath)
        assertEquals("en", endpoint.queryParameter("language"))
        assertEquals("manual", endpoint.queryParameter("variant"))
        assertEquals("ttml", endpoint.queryParameter("format"))
        assertEquals("en", endpoint.queryParameter("sourceLanguage"))
        assertEquals("English", endpoint.queryParameter("name"))
        assertEquals("application/ttml+xml", source.mimeType)
        assertFalse(source.url.contains("youtube.example"))
    }

    @Test
    fun `translated automatic track preserves its source identifiers`() {
        val source = subtitle(
            url = "https://youtube.example/timedtext?lang=en&tlang=fr&kind=asr&vssId=a.en",
            language = "fr",
        ).toYoutubeSubtitleSource(BASE_URL, VIDEO_ID)
        val endpoint = requireNotNull(source).url.toHttpUrl()

        assertTrue(source.isAutoGenerated)
        assertEquals("auto", endpoint.queryParameter("variant"))
        assertEquals("en", endpoint.queryParameter("sourceLanguage"))
        assertEquals("fr", endpoint.queryParameter("translation"))
    }

    @Test
    fun `automatic metadata remains usable when the signed URL is malformed`() {
        val source = subtitle(
            url = "expired signed URL",
            language = "es",
            autoGenerated = true,
        ).toYoutubeSubtitleSource(BASE_URL, VIDEO_ID)
        val endpoint = requireNotNull(source).url.toHttpUrl()

        assertEquals("auto", endpoint.queryParameter("variant"))
        assertNull(endpoint.queryParameter("sourceLanguage"))
        assertNull(endpoint.queryParameter("translation"))
    }

    @Test
    fun `invalid required identifiers never fall back to the signed URL`() {
        assertNull(subtitle(language = "").toYoutubeSubtitleSource(BASE_URL, VIDEO_ID))
        assertNull(subtitle().toYoutubeSubtitleSource(BASE_URL, ""))
        assertNull(subtitle().toYoutubeSubtitleSource("not a server", VIDEO_ID))
    }

    private fun subtitle(
        url: String = "https://youtube.example/timedtext?lang=en",
        language: String = "en",
        autoGenerated: Boolean = false,
    ) = SubtitleItem(
        url = url,
        mimeType = "text/xml",
        languageTag = language,
        displayLanguageName = language,
        isAutoGenerated = autoGenerated,
    )

    private companion object {
        const val BASE_URL = "https://instance.example/api/"
        const val VIDEO_ID = "Xj0Jtjg3lHQ"
    }
}
