package dev.typetype.android.feature.player

import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamSubtitleSource

internal fun Stream.initialQuality(): String {
    if (
        playbackContract == dev.typetype.android.domain.stream.StreamPlaybackContract.ServerSabr ||
        !hasAdaptiveSource()
    ) {
        return RECOMMENDED_QUALITY_KEY
    }
    return AUTO_QUALITY_KEY
}

internal fun Stream.initialAudioKey(
    defaultAudioLanguage: String,
    preferOriginalLanguage: Boolean,
): String? = null

internal fun Stream.initialSubtitleKey(
    subtitlesEnabled: Boolean,
    defaultSubtitleLanguage: String,
): String? {
    if (!subtitlesEnabled) return null
    val language = defaultSubtitleLanguage.takeIf { it.isNotBlank() }
    val localized = language?.let { target ->
        subtitles.firstOrNull { subtitle ->
            subtitle.languageTag.equals(target, ignoreCase = true) ||
                subtitle.languageTag.startsWith("$target-", ignoreCase = true)
        }
    }
    return (localized ?: subtitles.firstOrNull())?.selectionKey
}

internal fun Stream.hasAdaptiveSource(): Boolean =
    !serverHlsManifestUrl.isNullOrBlank() ||
        !serverDashManifestUrl.isNullOrBlank() ||
        !hlsUrl.isNullOrBlank() ||
        !dashMpdUrl.isNullOrBlank()

private val StreamSubtitleSource.selectionKey: String
    get() = languageTag.takeIf { it.isNotBlank() }
        ?.let { "$it:${isAutoGenerated}" }
        ?: url
