package dev.typetype.android.feature.player

import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.domain.stream.StreamVideoSource

internal fun Stream.initialQuality(defaultQuality: String): String {
    if (hasAdaptiveSource()) return AUTO_QUALITY_KEY
    val options = allVideoSources().qualityLabels()
    val targetHeight = defaultQuality.qualityHeight()
    return when {
        options.contains(defaultQuality) -> defaultQuality
        targetHeight == null -> options.firstOrNull()
        else -> options
            .filter { (it.qualityHeight() ?: 0) <= targetHeight }
            .maxByOrNull { it.qualityHeight() ?: 0 }
            ?: options.minByOrNull { it.qualityHeight() ?: Int.MAX_VALUE }
    } ?: defaultQuality
}

internal fun Stream.initialAudioKey(
    defaultAudioLanguage: String,
    preferOriginalLanguage: Boolean,
): String? = null

internal fun Stream.initialSubtitleKey(
    subtitlesEnabled: Boolean,
    defaultSubtitleLanguage: String,
): String? {
    if (!subtitlesEnabled) return null
    val language = defaultSubtitleLanguage.takeIf { it.isNotBlank() }
    val localized = language?.let { target ->
        subtitles.firstOrNull { subtitle ->
            subtitle.languageTag.equals(target, ignoreCase = true) ||
                subtitle.languageTag.startsWith("$target-", ignoreCase = true)
        }
    }
    return (localized ?: subtitles.firstOrNull())?.selectionKey
}

private fun Stream.allVideoSources(): List<StreamVideoSource> =
    (videoOnlyStreams + muxedVideoStreams).filter { it.url.isNotBlank() && it.height > 0 }

private fun Stream.hasAdaptiveSource(): Boolean =
    !serverHlsManifestUrl.isNullOrBlank() ||
        !serverDashManifestUrl.isNullOrBlank() ||
        !hlsUrl.isNullOrBlank() ||
        !dashMpdUrl.isNullOrBlank()

private fun List<StreamVideoSource>.qualityLabels(): List<String> =
    map { it.height }
        .distinct()
        .sortedDescending()
        .map { "${it}p" }

private val StreamSubtitleSource.selectionKey: String
    get() = languageTag.takeIf { it.isNotBlank() }
        ?.let { "$it:${isAutoGenerated}" }
        ?: url

private fun String.qualityHeight(): Int? =
    filter { it.isDigit() }.toIntOrNull()

private const val AUTO_QUALITY_KEY = "auto"
