package dev.typetype.android.feature.player

import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.runtime.remember
import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamSubtitleSource

internal class PlayerPlaybackSelectionState(
    stream: Stream,
    defaultAudioLanguage: String,
    subtitlesEnabled: Boolean,
    defaultSubtitleLanguage: String,
    preferOriginalLanguage: Boolean,
    preferredCodec: String = RECOMMENDED_CODEC_KEY,
    defaultPlaybackSpeed: Double = 1.0,
) {
    var selectedCodec by mutableStateOf(preferredCodec)
        private set
    var selectedQuality by mutableStateOf(stream.initialQuality())
        private set
    var selectedAudioKey by mutableStateOf(
        stream.initialAudioKey(defaultAudioLanguage, preferOriginalLanguage),
    )
        private set
    var selectedSubtitleKey by mutableStateOf(
        stream.initialSubtitleKey(subtitlesEnabled, defaultSubtitleLanguage),
    )
        private set
    var selectedSpeed by mutableFloatStateOf(normalizeDefaultPlaybackSpeed(defaultPlaybackSpeed))
        private set

    private var knownSubtitles = stream.subtitles
    private var subtitleSelectionManuallyChanged = false
    private var subtitlePreference = knownSubtitles
        .firstOrNull { it.key == selectedSubtitleKey }
        ?.preference

    fun updateStream(
        stream: Stream,
        subtitlesEnabled: Boolean,
        defaultSubtitleLanguage: String,
    ) {
        val updatedSubtitles = stream.subtitles
        if (updatedSubtitles.isEmpty()) return
        if (!subtitlesEnabled || subtitleSelectionManuallyChanged && selectedSubtitleKey == null) {
            knownSubtitles = updatedSubtitles
            return
        }
        val replacement = updatedSubtitles.firstOrNull { it.key == selectedSubtitleKey }
            ?: subtitlePreference?.let { preferred ->
                updatedSubtitles.firstOrNull { it.preference == preferred }
            }
        knownSubtitles = updatedSubtitles
        selectedSubtitleKey = replacement?.key ?: if (subtitleSelectionManuallyChanged) {
            null
        } else {
            stream.initialSubtitleKey(true, defaultSubtitleLanguage)
        }
        subtitlePreference = knownSubtitles
            .firstOrNull { it.key == selectedSubtitleKey }
            ?.preference
    }

    fun selectCodec(codec: String) {
        selectedCodec = codec
    }

    fun selectQuality(quality: String) {
        selectedQuality = quality
    }

    fun selectAudio(key: String?) {
        selectedAudioKey = key
    }

    fun selectSubtitle(key: String?) {
        selectedSubtitleKey = key
        subtitleSelectionManuallyChanged = true
        subtitlePreference = knownSubtitles.firstOrNull { it.key == key }?.preference
    }

    fun selectSpeed(speed: Float) {
        selectedSpeed = speed
    }
}

@Composable
internal fun rememberPlayerPlaybackSelectionState(
    stream: Stream,
    defaultQuality: String,
    defaultAudioLanguage: String,
    subtitlesEnabled: Boolean,
    defaultSubtitleLanguage: String,
    preferOriginalLanguage: Boolean,
    defaultPlaybackSpeed: Double,
    preferredCodec: String = RECOMMENDED_CODEC_KEY,
): PlayerPlaybackSelectionState {
    val state = remember(
        stream.id,
        defaultQuality,
        defaultAudioLanguage,
        subtitlesEnabled,
        defaultSubtitleLanguage,
        preferOriginalLanguage,
        defaultPlaybackSpeed,
        preferredCodec,
    ) {
        PlayerPlaybackSelectionState(
            stream = stream,
            defaultAudioLanguage = defaultAudioLanguage,
            subtitlesEnabled = subtitlesEnabled,
            defaultSubtitleLanguage = defaultSubtitleLanguage,
            preferOriginalLanguage = preferOriginalLanguage,
            defaultPlaybackSpeed = defaultPlaybackSpeed,
            preferredCodec = preferredCodec,
        )
    }
    LaunchedEffect(stream.subtitles, subtitlesEnabled, defaultSubtitleLanguage) {
        state.updateStream(stream, subtitlesEnabled, defaultSubtitleLanguage)
    }
    return state
}

internal fun normalizeDefaultPlaybackSpeed(speed: Double): Float =
    speed.takeIf(Double::isFinite)?.coerceIn(0.25, 4.0)?.toFloat() ?: 1f

private data class SubtitlePreference(
    val languageTag: String,
    val isAutoGenerated: Boolean,
)

private val StreamSubtitleSource.preference: SubtitlePreference
    get() = SubtitlePreference(languageTag.lowercase(), isAutoGenerated)
