package dev.typetype.android.feature.player.components

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.media3.common.Player
import dev.typetype.android.R
import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamPlaybackContract
import dev.typetype.android.feature.player.AUTO_QUALITY_KEY
import dev.typetype.android.feature.player.PlaybackCodecSupport
import dev.typetype.android.feature.player.PlayerDanmakuAction
import dev.typetype.android.feature.player.PlayerDanmakuState
import dev.typetype.android.feature.player.RECOMMENDED_CODEC_KEY
import dev.typetype.android.feature.player.RECOMMENDED_QUALITY_KEY
import dev.typetype.android.feature.player.hasAdaptiveSource
import dev.typetype.android.feature.player.state.PLAYBACK_SPEEDS
import dev.typetype.android.feature.player.state.ResizeMode

@kotlin.OptIn(ExperimentalMaterial3Api::class)
@Composable
internal fun PlaybackOptionsSheet(
    player: Player,
    stream: Stream,
    selectedCodec: String,
    selectedQuality: String,
    selectedAudioKey: String?,
    selectedSubtitleKey: String?,
    selectedSpeed: Float,
    codecSupport: PlaybackCodecSupport,
    resizeMode: ResizeMode,
    audioOnlyEnabled: Boolean,
    audioOnlyChanging: Boolean,
    showAudioOnly: Boolean,
    danmakuState: PlayerDanmakuState = PlayerDanmakuState(),
    onSelectCodec: (String) -> Unit,
    onSelectQuality: (String) -> Unit,
    onSelectAudio: (String?) -> Unit,
    onSelectSubtitle: (String?) -> Unit,
    onSelectSpeed: (Float) -> Unit,
    onSelectResizeMode: (ResizeMode) -> Unit,
    onAudioOnlyChange: (Boolean) -> Unit,
    onDanmakuAction: (PlayerDanmakuAction) -> Unit = {},
    onDismiss: () -> Unit,
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    val activeVideoFormat = rememberActiveVideoFormat(player)
    val autoLabel = stringResource(R.string.playback_options_auto)
    val recommendedLabel = stringResource(R.string.playback_options_recommended)
    val smartLabel = stringResource(R.string.playback_options_smart)
    val isServerSabr = stream.playbackContract == StreamPlaybackContract.ServerSabr
    val usesRecommendedSelection = isServerSabr || !stream.hasAdaptiveSource()
    val codecOptions = remember(stream, codecSupport) { stream.codecOptions(codecSupport) }
    val qualityOptions = remember(stream, selectedCodec, codecSupport) {
        stream.qualityOptions(selectedCodec, codecSupport)
    }
    val allCodecOptions = listOf(
        PlaybackPickerOption(
            RECOMMENDED_CODEC_KEY,
            smartLabel,
            stringResource(R.string.playback_options_smart_summary),
        ),
    ) + codecOptions
    val automaticOption = if (usesRecommendedSelection) {
        PlaybackPickerOption(
            RECOMMENDED_QUALITY_KEY,
            recommendedLabel,
            stringResource(R.string.playback_options_recommended_summary),
        )
    } else {
        PlaybackPickerOption(
            AUTO_QUALITY_KEY,
            autoLabel,
            stringResource(R.string.playback_options_auto_summary),
        )
    }
    val allQualityOptions = listOf(automaticOption) + qualityOptions
    val selectedCodecLabel = if (selectedCodec == RECOMMENDED_CODEC_KEY) {
        activeVideoFormat?.let { "$smartLabel · ${it.codec}" } ?: smartLabel
    } else {
        allCodecOptions.firstOrNull { it.key == selectedCodec }?.label ?: selectedCodec
    }
    val selectedQualityLabel = if (
        selectedQuality in setOf(AUTO_QUALITY_KEY, RECOMMENDED_QUALITY_KEY) &&
        activeVideoFormat != null
    ) {
        activeVideoFormat.qualityLabel
    } else {
        allQualityOptions.firstOrNull { it.key == selectedQuality }?.label
            ?: if (selectedQuality == AUTO_QUALITY_KEY) autoLabel else selectedQuality
    }
    val defaultLabel = stringResource(R.string.playback_options_default)
    val captionsLabel = stringResource(R.string.playback_options_captions)
    val originalLabel = stringResource(R.string.playback_options_original)
    val autoGeneratedLabel = stringResource(R.string.playback_options_auto_generated)
    val audioOptions = remember(stream.id, defaultLabel, originalLabel) {
        stream.audioOptions(defaultLabel, originalLabel)
    }
    val captionOptions = remember(stream.subtitles, captionsLabel, autoGeneratedLabel) {
        stream.captionOptions(captionsLabel, autoGeneratedLabel)
    }
    var page by remember { mutableStateOf(PlaybackOptionsPage.Main) }

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        containerColor = MaterialTheme.colorScheme.surface,
    ) {
        when (page) {
            PlaybackOptionsPage.Main -> PlaybackOptionsMainPage(
                codecLabel = selectedCodecLabel,
                qualityLabel = selectedQualityLabel,
                captionsLabel = captionOptions
                    .firstOrNull { it.key == selectedSubtitleKey }
                    ?.label
                    ?: stringResource(R.string.playback_options_off),
                audioLabel = audioOptions
                    .firstOrNull { it.key == selectedAudioKey }
                    ?.label
                    ?: stringResource(R.string.playback_options_default),
                speedLabel = "${formatSpeed(selectedSpeed)}x",
                resizeLabel = resizeMode.label(),
                audioOnlyEnabled = audioOnlyEnabled,
                audioOnlyChanging = audioOnlyChanging,
                showAudioOnly = showAudioOnly,
                showDanmaku = danmakuState.available,
                danmakuEnabled = danmakuState.enabled,
                danmakuSpeedLabel = "${formatSpeed(danmakuState.speed)}x",
                danmakuSizeLabel = "${(danmakuState.size * 100).toInt()}%",
                danmakuLoading = danmakuState.isLoading,
                danmakuLoadFailed = danmakuState.loadFailed,
                onOpenCodec = { page = PlaybackOptionsPage.Codec },
                onOpenQuality = { page = PlaybackOptionsPage.Quality },
                onOpenCaptions = { page = PlaybackOptionsPage.Captions },
                onOpenAudio = { page = PlaybackOptionsPage.Audio },
                onOpenSpeed = { page = PlaybackOptionsPage.Speed },
                onOpenResize = { page = PlaybackOptionsPage.Resize },
                onAudioOnlyChange = onAudioOnlyChange,
                onDanmakuChange = { onDanmakuAction(PlayerDanmakuAction.SetEnabled(it)) },
                onOpenDanmakuSpeed = { page = PlaybackOptionsPage.DanmakuSpeed },
                onOpenDanmakuSize = { page = PlaybackOptionsPage.DanmakuSize },
            )
            PlaybackOptionsPage.Codec -> PickerPage(
                title = stringResource(R.string.playback_options_codec),
                options = allCodecOptions,
                selectedKey = selectedCodec,
                emptyLabel = smartLabel,
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { key ->
                    key?.let(onSelectCodec)
                    onDismiss()
                },
            )
            PlaybackOptionsPage.Quality -> PickerPage(
                title = stringResource(R.string.playback_options_quality),
                options = allQualityOptions,
                selectedKey = selectedQuality,
                emptyLabel = automaticOption.label,
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { key ->
                    key?.let(onSelectQuality)
                    onDismiss()
                },
            )
            PlaybackOptionsPage.Audio -> PickerPage(
                title = stringResource(R.string.playback_options_audio),
                options = listOf(PlaybackPickerOption(null, stringResource(R.string.playback_options_default))) +
                    audioOptions,
                selectedKey = selectedAudioKey,
                emptyLabel = stringResource(R.string.playback_options_default),
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = {
                    onSelectAudio(it)
                    onDismiss()
                },
            )
            PlaybackOptionsPage.Captions -> PickerPage(
                title = stringResource(R.string.playback_options_captions),
                options = listOf(PlaybackPickerOption(null, stringResource(R.string.playback_options_off))) +
                    captionOptions,
                selectedKey = selectedSubtitleKey,
                emptyLabel = stringResource(R.string.playback_options_off),
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = {
                    onSelectSubtitle(it)
                    onDismiss()
                },
            )
            PlaybackOptionsPage.Speed -> PickerPage(
                title = stringResource(R.string.playback_options_speed),
                options = PLAYBACK_SPEEDS.map { PlaybackPickerOption(it.toString(), "${formatSpeed(it)}x") },
                selectedKey = selectedSpeed.toString(),
                emptyLabel = stringResource(R.string.playback_options_default),
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { key ->
                    key?.toFloatOrNull()?.let(onSelectSpeed)
                    onDismiss()
                },
            )
            PlaybackOptionsPage.Resize -> PickerPage(
                title = stringResource(R.string.playback_options_image),
                options = resizeModeOptions(),
                selectedKey = resizeMode.name,
                emptyLabel = resizeMode.label(),
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { key ->
                    key?.let(ResizeMode::valueOf)?.let(onSelectResizeMode)
                    onDismiss()
                },
            )
            PlaybackOptionsPage.DanmakuSpeed -> PickerPage(
                title = stringResource(R.string.settings_player_danmaku_speed),
                options = DANMAKU_VALUES.map {
                    PlaybackPickerOption(it.toString(), "${formatSpeed(it)}x")
                },
                selectedKey = danmakuState.speed.toString(),
                emptyLabel = "${formatSpeed(danmakuState.speed)}x",
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { value ->
                    value?.toFloatOrNull()?.let {
                        onDanmakuAction(PlayerDanmakuAction.SetSpeed(it))
                    }
                },
            )
            PlaybackOptionsPage.DanmakuSize -> PickerPage(
                title = stringResource(R.string.settings_player_danmaku_size),
                options = DANMAKU_VALUES.map {
                    PlaybackPickerOption(it.toString(), "${(it * 100).toInt()}%")
                },
                selectedKey = danmakuState.size.toString(),
                emptyLabel = "${(danmakuState.size * 100).toInt()}%",
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { value ->
                    value?.toFloatOrNull()?.let {
                        onDanmakuAction(PlayerDanmakuAction.SetSize(it))
                    }
                },
            )
        }
    }
}

@Composable
private fun PickerPage(
    title: String,
    options: List<PlaybackPickerOption>,
    selectedKey: String?,
    emptyLabel: String,
    onBack: () -> Unit,
    onSelect: (String?) -> Unit,
) {
    LazyColumn(
        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp),
        verticalArrangement = Arrangement.spacedBy(2.dp),
    ) {
        item { PlaybackOptionsPageHeader(title = title, onBack = onBack) }
        if (options.isEmpty()) {
            item { PlaybackOptionsHint(text = emptyLabel) }
        }
        items(options, key = { it.key ?: "off" }) { option ->
            val decoderLabel = when (option.decoderSupport) {
                dev.typetype.android.feature.player.DecoderSupport.Hardware ->
                    stringResource(R.string.playback_options_hardware_decoder)
                dev.typetype.android.feature.player.DecoderSupport.Software ->
                    stringResource(R.string.playback_options_software_decoder)
                else -> null
            }
            PlaybackOptionsRadioRow(
                label = option.label,
                supportingLabel = listOfNotNull(option.supportingLabel, decoderLabel)
                    .takeIf { it.isNotEmpty() }
                    ?.joinToString(" · "),
                selected = option.key == selectedKey,
                onSelect = { onSelect(option.key) },
            )
        }
    }
}

private enum class PlaybackOptionsPage {
    Main,
    Codec,
    Quality,
    Captions,
    Audio,
    Speed,
    Resize,
    DanmakuSpeed,
    DanmakuSize,
}

private val DANMAKU_VALUES = listOf(0.5f, 0.75f, 1f, 1.25f, 1.5f, 2f)

private fun formatSpeed(value: Float): String =
    if (value % 1f == 0f) value.toInt().toString() else value.toString()

@Composable
private fun ResizeMode.label(): String = when (this) {
    ResizeMode.Fit -> stringResource(R.string.player_resize_fit)
    ResizeMode.Crop -> stringResource(R.string.player_resize_crop)
    ResizeMode.Stretch -> stringResource(R.string.player_resize_stretch)
}

@Composable
private fun resizeModeOptions(): List<PlaybackPickerOption> =
    listOf(ResizeMode.Fit, ResizeMode.Stretch, ResizeMode.Crop)
        .map { PlaybackPickerOption(it.name, it.label()) }
