package dev.typetype.android.feature.player.components

import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamAudioSource
import dev.typetype.android.domain.stream.StreamPlaybackContract
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.domain.stream.StreamVideoSource
import dev.typetype.android.domain.stream.isServerSabrVideoFormat
import dev.typetype.android.feature.player.DecoderSupport
import dev.typetype.android.feature.player.PlaybackCodecSupport
import dev.typetype.android.feature.player.RECOMMENDED_CODEC_KEY
import dev.typetype.android.feature.player.codecDisplayName
import dev.typetype.android.feature.player.codecSelectionKey
import dev.typetype.android.feature.player.key

internal fun Stream.codecOptions(codecSupport: PlaybackCodecSupport): List<PlaybackPickerOption> =
    supportedVideoSources(codecSupport)
        .groupBy { it.source.codecSelectionKey() }
        .map { (codec, candidates) ->
            PlaybackPickerOption(
                key = codec,
                label = codec.codecDisplayName(),
                decoderSupport = candidates.maxBy { it.support.rank }.support,
            )
        }
        .sortedBy { CODEC_ORDER.indexOf(it.key).takeIf { index -> index >= 0 } ?: Int.MAX_VALUE }

internal fun Stream.qualityOptions(
    selectedCodec: String,
    codecSupport: PlaybackCodecSupport,
): List<PlaybackPickerOption> = supportedVideoSources(codecSupport)
    .filter {
        selectedCodec == RECOMMENDED_CODEC_KEY ||
            it.source.codecSelectionKey() == selectedCodec
    }
    .groupBy { it.source.height }
    .map { (height, candidates) ->
        val best = candidates.maxWith(
            compareBy<SupportedVideoSource> { it.support.rank }
                .thenBy { it.source.fps }
                .thenBy { it.source.bitrate ?: 0 },
        )
        PlaybackPickerOption(
            key = "${height}p",
            label = best.source.qualityLabel(),
            supportingLabel = best.source.formatDetails(),
            decoderSupport = best.support,
        )
    }
    .sortedByDescending { it.key?.filter(Char::isDigit)?.toIntOrNull() ?: 0 }

private fun Stream.supportedVideoSources(
    codecSupport: PlaybackCodecSupport,
): List<SupportedVideoSource> {
    val isServerSabr = playbackContract == StreamPlaybackContract.ServerSabr
    val supportedAudioAvailable = (sabrAudioStreams + audioStreams).any {
        it.url.isNotBlank() && codecSupport.audio(it) != DecoderSupport.Unsupported
    }
    val sources = if (isServerSabr) sabrVideoStreams else videoOnlyStreams + muxedVideoStreams
    return sources
        .filter { it.url.isNotBlank() && it.height > 0 }
        .filter { !isServerSabr || it.itag > 0 && isServerSabrVideoFormat(it.codec) }
        .filter { !it.isVideoOnly || supportedAudioAvailable }
        .mapNotNull { source ->
            val support = codecSupport.video(source)
            source.takeIf { support != DecoderSupport.Unsupported }
                ?.let { SupportedVideoSource(it, support) }
        }
        .distinctBy { listOf(it.source.codecSelectionKey(), it.source.height, it.source.fps) }
}

internal fun Stream.audioOptions(defaultLabel: String, originalLabel: String): List<PlaybackPickerOption> =
    (sabrAudioStreams + audioStreams)
        .filter { it.url.isNotBlank() }
        .distinctBy { it.key }
        .map { PlaybackPickerOption(it.key, it.label(defaultLabel, originalLabel)) }

internal fun Stream.captionOptions(captionsLabel: String, autoGeneratedLabel: String): List<PlaybackPickerOption> =
    subtitles
        .filter { it.url.isNotBlank() }
        .distinctBy { it.key }
        .map { PlaybackPickerOption(it.key, it.label(captionsLabel, autoGeneratedLabel)) }

private fun StreamAudioSource.label(defaultLabel: String, originalLabel: String): String {
    val locale = audioLocale?.takeIf { it.isNotBlank() }
    val trackName = audioTrackName?.takeIf { it.isNotBlank() }
    val baseName = trackName ?: locale
    val format = mimeType.substringBefore(";").substringAfter("/").takeIf { it.isNotBlank() }
    val label = listOfNotNull(
        baseName,
        bitrate?.let(::formatBitrate),
        format,
    ).joinToString(" - ").ifBlank { defaultLabel }
    val alreadyOriginal = trackName?.contains(originalLabel, ignoreCase = true) == true
    return if (isOriginal && !alreadyOriginal) "$label - $originalLabel" else label
}

private fun StreamSubtitleSource.label(captionsLabel: String, autoGeneratedLabel: String): String =
    buildString {
        append(
            displayLanguageName
                .ifBlank { languageTag.ifBlank { captionsLabel } }
                .removeAutoGeneratedSuffix(),
        )
        if (isAutoGenerated) append(" ($autoGeneratedLabel)")
    }

private fun String.removeAutoGeneratedSuffix(): String =
    replace(AUTO_GENERATED_SUFFIX, "").trimEnd()

private fun StreamVideoSource.qualityLabel(): String =
    if (resolution.contains("HDR", ignoreCase = true)) "${height}p HDR" else "${height}p"

private fun StreamVideoSource.formatDetails(): String? = listOfNotNull(
    fps.takeIf { it > 0 }?.let { "$it fps" },
    bitrate?.takeIf { it > 0 }?.let(::formatBitrate),
).takeIf { it.isNotEmpty() }?.joinToString(" · ")

private fun formatBitrate(bitrate: Int): String = when {
    bitrate >= 1_000_000 -> {
        val tenths = bitrate / 100_000
        if (tenths % 10 == 0) "${tenths / 10} Mbps" else "${tenths / 10}.${tenths % 10} Mbps"
    }
    bitrate >= 1_000 -> "${bitrate / 1_000} kbps"
    else -> "$bitrate bps"
}

private data class SupportedVideoSource(
    val source: StreamVideoSource,
    val support: DecoderSupport,
)

private val CODEC_ORDER = listOf("h264", "vp9", "av1", "hevc", "other")
private val AUTO_GENERATED_SUFFIX = Regex(
    """\s*\((?:auto[- ]generated|automatically generated)\)\s*$""",
    RegexOption.IGNORE_CASE,
)
