package dev.typetype.android.feature.player.components

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Audiotrack
import androidx.compose.material.icons.filled.ClosedCaption
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material.icons.filled.Speed
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import dev.typetype.android.R
import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamAudioSource
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.feature.player.state.PLAYBACK_SPEEDS

@kotlin.OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PlaybackOptionsSheet(
    stream: Stream,
    selectedQuality: String,
    selectedAudioKey: String?,
    selectedSubtitleKey: String?,
    selectedSpeed: Float,
    onSelectQuality: (String) -> Unit,
    onSelectAudio: (String?) -> Unit,
    onSelectSubtitle: (String?) -> Unit,
    onSelectSpeed: (Float) -> Unit,
    onDismiss: () -> Unit,
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = false)
    val defaultLabel = stringResource(R.string.playback_options_default)
    val captionsLabel = stringResource(R.string.playback_options_captions)
    val originalLabel = stringResource(R.string.playback_options_original)
    val autoGeneratedLabel = stringResource(R.string.playback_options_auto_generated)
    val qualityOptions = remember(stream.id) { stream.qualityOptions() }
    val audioOptions = remember(stream.id, defaultLabel, originalLabel) {
        stream.audioOptions(defaultLabel, originalLabel)
    }
    val captionOptions = remember(stream.id, captionsLabel, autoGeneratedLabel) {
        stream.captionOptions(captionsLabel, autoGeneratedLabel)
    }
    var page by remember { mutableStateOf(PlaybackOptionsPage.Main) }

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        containerColor = MaterialTheme.colorScheme.surface,
    ) {
        when (page) {
            PlaybackOptionsPage.Main -> PlaybackOptionsMainPage(
                qualityLabel = selectedQuality,
                captionsLabel = captionOptions
                    .firstOrNull { it.key == selectedSubtitleKey }
                    ?.label
                    ?: stringResource(R.string.playback_options_off),
                audioLabel = audioOptions
                    .firstOrNull { it.key == selectedAudioKey }
                    ?.label
                    ?: stringResource(R.string.playback_options_default),
                speedLabel = "${formatSpeed(selectedSpeed)}x",
                onOpenQuality = { page = PlaybackOptionsPage.Quality },
                onOpenCaptions = { page = PlaybackOptionsPage.Captions },
                onOpenAudio = { page = PlaybackOptionsPage.Audio },
                onOpenSpeed = { page = PlaybackOptionsPage.Speed },
            )
            PlaybackOptionsPage.Quality -> PickerPage(
                title = stringResource(R.string.playback_options_quality),
                options = listOf(
                    PickerOption("auto", stringResource(R.string.playback_options_auto)),
                ) + qualityOptions.map { PickerOption(it, it) },
                selectedKey = selectedQuality,
                emptyLabel = stringResource(R.string.playback_options_auto),
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { key -> key?.let(onSelectQuality) },
            )
            PlaybackOptionsPage.Audio -> PickerPage(
                title = stringResource(R.string.playback_options_audio),
                options = listOf(PickerOption(null, stringResource(R.string.playback_options_default))) +
                    audioOptions,
                selectedKey = selectedAudioKey,
                emptyLabel = stringResource(R.string.playback_options_default),
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { onSelectAudio(it) },
            )
            PlaybackOptionsPage.Captions -> PickerPage(
                title = stringResource(R.string.playback_options_captions),
                options = listOf(PickerOption(null, stringResource(R.string.playback_options_off))) +
                    captionOptions,
                selectedKey = selectedSubtitleKey,
                emptyLabel = stringResource(R.string.playback_options_off),
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { onSelectSubtitle(it) },
            )
            PlaybackOptionsPage.Speed -> PickerPage(
                title = stringResource(R.string.playback_options_speed),
                options = PLAYBACK_SPEEDS.map { PickerOption(it.toString(), "${formatSpeed(it)}x") },
                selectedKey = selectedSpeed.toString(),
                emptyLabel = stringResource(R.string.playback_options_default),
                onBack = { page = PlaybackOptionsPage.Main },
                onSelect = { key -> key?.toFloatOrNull()?.let(onSelectSpeed) },
            )
        }
    }
}

@Composable
private fun PlaybackOptionsMainPage(
    qualityLabel: String,
    captionsLabel: String,
    audioLabel: String,
    speedLabel: String,
    onOpenQuality: () -> Unit,
    onOpenCaptions: () -> Unit,
    onOpenAudio: () -> Unit,
    onOpenSpeed: () -> Unit,
) {
    LazyColumn(
        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
        verticalArrangement = Arrangement.spacedBy(2.dp),
    ) {
        item {
            PlaybackOptionsMenuRow(
                icon = Icons.Filled.Settings,
                title = stringResource(R.string.playback_options_quality),
                value = qualityLabel,
                onClick = onOpenQuality,
            )
        }
        item {
            PlaybackOptionsMenuRow(
                icon = Icons.Filled.ClosedCaption,
                title = stringResource(R.string.playback_options_captions),
                value = captionsLabel,
                onClick = onOpenCaptions,
            )
        }
        item {
            PlaybackOptionsMenuRow(
                icon = Icons.Filled.Audiotrack,
                title = stringResource(R.string.playback_options_audio),
                value = audioLabel,
                onClick = onOpenAudio,
            )
        }
        item {
            PlaybackOptionsMenuRow(
                icon = Icons.Filled.Speed,
                title = stringResource(R.string.playback_options_speed),
                value = speedLabel,
                onClick = onOpenSpeed,
            )
        }
    }
}

@Composable
private fun PickerPage(
    title: String,
    options: List<PickerOption>,
    selectedKey: String?,
    emptyLabel: String,
    onBack: () -> Unit,
    onSelect: (String?) -> Unit,
) {
    LazyColumn(
        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp),
        verticalArrangement = Arrangement.spacedBy(2.dp),
    ) {
        item { PlaybackOptionsPageHeader(title = title, onBack = onBack) }
        if (options.isEmpty()) {
            item { PlaybackOptionsHint(text = emptyLabel) }
        }
        items(options, key = { it.key ?: "off" }) { option ->
            PlaybackOptionsRadioRow(
                label = option.label,
                selected = option.key == selectedKey,
                onSelect = { onSelect(option.key) },
            )
        }
    }
}

private fun Stream.qualityOptions(): List<String> =
    (videoOnlyStreams + muxedVideoStreams)
        .filter { it.url.isNotBlank() && it.height > 0 }
        .map { it.height }
        .distinct()
        .sortedDescending()
        .map { "${it}p" }
private fun Stream.audioOptions(defaultLabel: String, originalLabel: String): List<PickerOption> =
    audioStreams
        .filter { it.url.isNotBlank() }
        .distinctBy { it.key }
        .map { PickerOption(it.key, it.label(defaultLabel, originalLabel)) }
private fun Stream.captionOptions(captionsLabel: String, autoGeneratedLabel: String): List<PickerOption> =
    subtitles
        .filter { it.url.isNotBlank() }
        .distinctBy { it.key }
        .map { PickerOption(it.key, it.label(captionsLabel, autoGeneratedLabel)) }
private val StreamAudioSource.key: String
    get() = audioTrackId?.takeIf { it.isNotBlank() }
        ?: audioLocale?.takeIf { it.isNotBlank() }
        ?: url
private fun StreamAudioSource.label(defaultLabel: String, originalLabel: String): String {
    val locale = audioLocale?.takeIf { it.isNotBlank() }
    val trackName = audioTrackName?.takeIf { it.isNotBlank() }
    val baseName = trackName ?: locale
    val format = mimeType.substringBefore(";").substringAfter("/").takeIf { it.isNotBlank() }
    val label = listOfNotNull(
        baseName,
        bitrate?.let { "$it kbps" },
        format,
    ).joinToString(" - ").ifBlank { defaultLabel }
    val alreadyOriginal = trackName?.contains(originalLabel, ignoreCase = true) == true
    return if (isOriginal && !alreadyOriginal) "$label - $originalLabel" else label
}
private val StreamSubtitleSource.key: String
    get() = languageTag.takeIf { it.isNotBlank() }
        ?.let { "$it:${isAutoGenerated}" }
        ?: url
private fun StreamSubtitleSource.label(captionsLabel: String, autoGeneratedLabel: String): String =
    buildString {
        append(displayLanguageName.ifBlank { languageTag.ifBlank { captionsLabel } })
        if (isAutoGenerated) append(" ($autoGeneratedLabel)")
    }
private data class PickerOption(
    val key: String?,
    val label: String,
)

private enum class PlaybackOptionsPage {
    Main,
    Quality,
    Captions,
    Audio,
    Speed,
}

private fun formatSpeed(value: Float): String =
    if (value % 1f == 0f) value.toInt().toString() else value.toString()
