package dev.typetype.android.feature.player.components

import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamAudioSource
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.feature.player.key

fun Stream.qualityOptions(): List<String> =
    (videoOnlyStreams + muxedVideoStreams)
        .filter { it.url.isNotBlank() && it.height > 0 }
        .map { it.height }
        .distinct()
        .sortedDescending()
        .map { "${it}p" }

fun Stream.audioOptions(defaultLabel: String, originalLabel: String): List<PlaybackPickerOption> =
    audioStreams
        .filter { it.url.isNotBlank() }
        .distinctBy { it.key }
        .map { PlaybackPickerOption(it.key, it.label(defaultLabel, originalLabel)) }

fun Stream.captionOptions(captionsLabel: String, autoGeneratedLabel: String): List<PlaybackPickerOption> =
    subtitles
        .filter { it.url.isNotBlank() }
        .distinctBy { it.key }
        .map { PlaybackPickerOption(it.key, it.label(captionsLabel, autoGeneratedLabel)) }

private fun StreamAudioSource.label(defaultLabel: String, originalLabel: String): String {
    val locale = audioLocale?.takeIf { it.isNotBlank() }
    val trackName = audioTrackName?.takeIf { it.isNotBlank() }
    val baseName = trackName ?: locale
    val format = mimeType.substringBefore(";").substringAfter("/").takeIf { it.isNotBlank() }
    val label = listOfNotNull(
        baseName,
        bitrate?.let { "$it kbps" },
        format,
    ).joinToString(" - ").ifBlank { defaultLabel }
    val alreadyOriginal = trackName?.contains(originalLabel, ignoreCase = true) == true
    return if (isOriginal && !alreadyOriginal) "$label - $originalLabel" else label
}

private fun StreamSubtitleSource.label(captionsLabel: String, autoGeneratedLabel: String): String =
    buildString {
        append(displayLanguageName.ifBlank { languageTag.ifBlank { captionsLabel } })
        if (isAutoGenerated) append(" ($autoGeneratedLabel)")
    }
