package video.typetype.tv.data

import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.launch
import video.typetype.sdk.core.PlaybackOpenRequest
import video.typetype.sdk.core.ServiceId
import video.typetype.sdk.core.SubtitleTrack
import video.typetype.sdk.core.TypeTypeResult

public fun TvViewModel.switchVideoTrack(itag: Int, positionMilliseconds: Long) {
    val state = mutableState.value
    val stream = state.stream ?: return
    val video = state.selectedVideo ?: return
    val tracks = stream.selectTvPlaybackTracks(
        isVideoSupported,
        preferredVideoItag = itag,
        preferredAudioItag = state.selectedAudioItag,
        preferredAudioTrackId = state.selectedAudioTrackId,
    ) ?: return
    reopenPlayback(
        video,
        tracks.video.itag,
        tracks.audio.itag,
        tracks.audio.audioTrackId,
        state.subtitleTrack(),
        positionMilliseconds,
    )
}

public fun TvViewModel.switchAudioTrack(itag: Int, trackId: String?, positionMilliseconds: Long) {
    val state = mutableState.value
    val stream = state.stream ?: return
    val video = state.selectedVideo ?: return
    val tracks = stream.selectTvPlaybackTracks(
        isVideoSupported,
        preferredVideoItag = state.selectedVideoItag,
        preferredAudioItag = itag,
        preferredAudioTrackId = trackId,
    ) ?: return
    reopenPlayback(
        video,
        tracks.video.itag,
        tracks.audio.itag,
        tracks.audio.audioTrackId,
        state.subtitleTrack(),
        positionMilliseconds,
    )
}

public fun TvViewModel.switchSubtitle(
    language: String?,
    auto: Boolean,
    name: String?,
    positionMilliseconds: Long,
) {
    val state = mutableState.value
    val stream = state.stream ?: return
    val video = state.selectedVideo ?: return
    val subtitle = if (language == null) null else state.playback?.subtitles?.firstOrNull {
        it.languageTag == language && it.isAutoGenerated == auto && it.name == name
    }
    if (state.selectedService != ServiceId.YOUTUBE) {
        val standard = stream.standardPlaybackSession(state.selectedService) ?: return
        mutableState.value = state.copy(
            playback = standard.copy(startTimeMilliseconds = positionMilliseconds.coerceAtLeast(0L)),
            selectedSubtitleLanguage = subtitle?.languageTag,
            selectedSubtitleAuto = subtitle?.isAutoGenerated ?: false,
            selectedSubtitleName = subtitle?.name,
            errorMessage = null,
        )
        return
    }
    val tracks = stream.selectTvPlaybackTracks(
        isVideoSupported,
        preferredVideoItag = state.selectedVideoItag,
        preferredAudioItag = state.selectedAudioItag,
        preferredAudioTrackId = state.selectedAudioTrackId,
    ) ?: return
    reopenPlayback(
        video,
        tracks.video.itag,
        tracks.audio.itag,
        tracks.audio.audioTrackId,
        subtitle,
        positionMilliseconds,
    )
}

private fun TvViewModel.reopenPlayback(
    video: video.typetype.sdk.core.Video,
    videoItag: Int,
    audioItag: Int,
    audioTrackId: String?,
    subtitle: SubtitleTrack?,
    positionMilliseconds: Long,
) {
    val stream = mutableState.value.stream ?: return
    val state = mutableState.value
    if (state.selectedService != ServiceId.YOUTUBE) {
        val standard = stream.standardPlaybackSession(state.selectedService) ?: return
        mutableState.value = state.copy(
            playback = standard.copy(startTimeMilliseconds = positionMilliseconds.coerceAtLeast(0L)),
            selectedSubtitleLanguage = subtitle?.languageTag,
            selectedSubtitleAuto = subtitle?.isAutoGenerated ?: false,
            selectedSubtitleName = subtitle?.name,
            errorMessage = null,
        )
        return
    }
    viewModelScope.launch {
        mutableState.value = mutableState.value.copy(isLoadingDetails = true, errorMessage = null)
        when (val result = client.playback.open(
            PlaybackOpenRequest(
                videoUrl = video.url,
                videoItag = videoItag,
                audioItag = audioItag,
                audioTrackId = audioTrackId,
                startTimeMilliseconds = positionMilliseconds.coerceAtLeast(0L),
                isLive = stream.isLive,
            ),
        )) {
            is TypeTypeResult.Success -> mutableState.value = mutableState.value.copy(
                playback = result.value,
                selectedVideoItag = result.value.selectedVideoItag ?: videoItag,
                selectedAudioItag = result.value.selectedAudioItag ?: audioItag,
                selectedAudioTrackId = result.value.audioTrackId ?: audioTrackId,
                selectedSubtitleLanguage = subtitle?.languageTag,
                selectedSubtitleAuto = subtitle?.isAutoGenerated ?: false,
                selectedSubtitleName = subtitle?.name,
                isLoadingDetails = false,
            )
            is TypeTypeResult.Failure -> mutableState.value = mutableState.value.copy(
                isLoadingDetails = false,
                errorMessage = "The new playback track could not be loaded. ${result.error.toUserMessage()}",
            )
        }
    }
}

private fun TvAppState.subtitleTrack(): SubtitleTrack? = playback?.subtitles?.firstOrNull {
    it.languageTag == selectedSubtitleLanguage &&
        it.isAutoGenerated == selectedSubtitleAuto &&
        it.name == selectedSubtitleName
}
