package dev.typetype.android.feature.player

import dev.typetype.android.domain.stream.SabrPlaybackBinding
import dev.typetype.android.domain.stream.SabrPlaybackRepository
import dev.typetype.android.domain.stream.SabrPlaybackSelection
import dev.typetype.android.domain.stream.SabrPlaybackSession
import dev.typetype.android.domain.stream.SabrPlaybackTarget
import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamAudioSource
import dev.typetype.android.domain.stream.StreamPlaybackContract
import dev.typetype.android.domain.stream.StreamRequestScope
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.domain.stream.StreamVideoSource
import dev.typetype.android.domain.stream.sabrPlaybackTarget
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Test

class PlayerSabrPlaybackTest {
    @Test
    fun `initial position is part of shared session creation`() = runBlocking {
        val repository = RecordingRepository()
        val playback = PlayerSabrPlayback(repository) { _, _ -> }

        val result = playback.prepare(stream(), selection(), 91_000L)

        assertEquals(91_000L, repository.startPositionMs)
        assertEquals(repository.session.copy(startTimeMs = 91_000L), result)
        assertEquals(0, repository.seekCount)
    }

    @Test
    fun `prepared shared session is reported to the player loader`() = runBlocking {
        val repository = RecordingRepository()
        var reported: SabrPlaybackSession? = null
        val playback = PlayerSabrPlayback(
            repository = repository,
            onPrepared = { _, session -> reported = session },
            onFailure = { _, _ -> },
        )

        val result = playback.prepare(stream(), selection(), 0L)

        assertEquals(result, reported)
    }

    @Test
    fun `activation consumes the matching preloaded session`() = runBlocking {
        val repository = RecordingRepository()
        val stream = stream()
        val selection = selection()
        val preloads = SabrPlaybackPreloadStore { 0L }
        preloads.reserve(stream.sabrPlaybackTarget(selection)).result.complete(
            Result.success(repository.session),
        )
        val playback = PlayerSabrPlayback(
            repository = repository,
            preloads = preloads,
            onFailure = { _, _ -> },
        )

        val result = playback.prepare(stream, selection, 0L)

        assertEquals(repository.session, result)
        assertEquals(0, repository.prepareCount)
    }

    @Test
    fun `resume position repositions the matching preload`() = runBlocking {
        val repository = RecordingRepository()
        val stream = stream()
        val selection = selection()
        val preloads = SabrPlaybackPreloadStore { 0L }
        preloads.reserve(stream.sabrPlaybackTarget(selection)).result.complete(
            Result.success(repository.session),
        )
        val playback = PlayerSabrPlayback(
            repository = repository,
            preloads = preloads,
            onFailure = { _, _ -> },
        )

        val result = playback.prepare(stream, selection, 4_000L)

        assertEquals(4_000L, result?.startTimeMs)
        assertEquals(0, repository.prepareCount)
        assertEquals(1, repository.seekCount)
    }

    @Test
    fun `stream metadata remains authoritative for subtitles`() {
        val generic = listOf(
            StreamSubtitleSource(
                url = "https://instance.example/api/subtitles/en.vtt",
                mimeType = "text/vtt",
                languageTag = "en",
                displayLanguageName = "English",
                isAutoGenerated = false,
                trackId = "en-manual",
            ),
        )
        val source = PlayableSource(
            url = session().manifestUrl,
            mimeType = "application/dash+xml",
            sabrSession = session(),
        )

        assertEquals(generic, source.playbackSubtitles(generic))
    }

    private class RecordingRepository : SabrPlaybackRepository {
        val session = session()
        var startPositionMs: Long? = null
        var seekCount = 0
        var prepareCount = 0

        override suspend fun prepare(target: SabrPlaybackTarget) =
            Result.success(session)

        override suspend fun prepare(
            target: SabrPlaybackTarget,
            startTimeMs: Long,
        ): Result<SabrPlaybackSession> {
            prepareCount++
            startPositionMs = startTimeMs
            return Result.success(session.copy(startTimeMs = startTimeMs))
        }

        override suspend fun seek(
            target: SabrPlaybackTarget,
            binding: SabrPlaybackBinding,
            startTimeMs: Long,
        ): Result<SabrPlaybackSession> {
            seekCount++
            return Result.success(session.copy(startTimeMs = startTimeMs))
        }
    }

    companion object {
        private fun stream() = Stream(
            playbackContract = StreamPlaybackContract.ServerSabr,
            id = "video",
            title = "Video",
            uploaderName = "Channel",
            uploaderAvatarUrl = "",
            uploaderUrl = "",
            uploaderSubscriberCount = 0,
            uploaderVerified = false,
            thumbnailUrl = "",
            description = "",
            durationSeconds = 120,
            viewCount = 0,
            likeCount = 0,
            dislikeCount = 0,
            uploadedAtMillis = 0,
            hlsUrl = null,
            dashMpdUrl = null,
            progressiveUrl = null,
            serverDashManifestUrl = null,
            serverHlsManifestUrl = null,
            requestScope = StreamRequestScope("server", "account", "https://instance.example/api/"),
            startPositionMillis = 0,
        )

        private fun selection() = SabrPlaybackSelection(
            video = StreamVideoSource(
                url = "https://instance.example/api/sabr/manifest/video",
                mimeType = "video/mp4",
                codec = "avc1.640028",
                resolution = "1080p",
                width = 1920,
                height = 1080,
                fps = 30,
                bitrate = 4_000_000,
                isVideoOnly = true,
                itag = 137,
            ),
            audio = StreamAudioSource(
                url = "https://instance.example/api/sabr/manifest/video",
                mimeType = "audio/mp4",
                codec = "mp4a.40.2",
                bitrate = 128_000,
                quality = "medium",
                audioTrackId = "en.0",
                audioTrackName = "English",
                audioLocale = "en",
                isOriginal = true,
                itag = 140,
            ),
        )

        private fun session() = SabrPlaybackSession(
            sessionId = "session",
            manifestUrl = "https://instance.example/api/sabr/playback/session/manifest",
            generation = 0,
            videoItag = 137,
            audioItag = 140,
            audioTrackId = "en.0",
            startTimeMs = 0,
            windowEndMs = 30_000,
            durationMs = 120_000,
            endOfStream = false,
        )
    }
}
