package dev.typetype.android.feature.player

import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamPlaybackContract
import dev.typetype.android.domain.stream.StreamSubtitleSource
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

class PlayerPlaybackSelectionStateTest {
    @Test
    fun `enabled subtitles are selected when late metadata arrives`() {
        val bootstrap = stream()
        val state = PlayerPlaybackSelectionState(
            stream = bootstrap,
            defaultAudioLanguage = "",
            subtitlesEnabled = true,
            defaultSubtitleLanguage = "fr",
            preferOriginalLanguage = false,
        )

        assertNull(state.selectedSubtitleKey)
        state.updateStream(
            bootstrap.copy(subtitles = listOf(subtitle("en"), subtitle("fr"))),
            subtitlesEnabled = true,
            defaultSubtitleLanguage = "fr",
        )

        assertEquals("fr:false", state.selectedSubtitleKey)
    }

    @Test
    fun `manual subtitle off is preserved across metadata refreshes`() {
        val initial = stream().copy(subtitles = listOf(subtitle("en")))
        val state = PlayerPlaybackSelectionState(
            stream = initial,
            defaultAudioLanguage = "",
            subtitlesEnabled = true,
            defaultSubtitleLanguage = "en",
            preferOriginalLanguage = false,
        )

        state.selectSubtitle(null)
        state.updateStream(
            initial.copy(subtitles = listOf(subtitle("en"), subtitle("fr"))),
            subtitlesEnabled = true,
            defaultSubtitleLanguage = "fr",
        )

        assertNull(state.selectedSubtitleKey)
    }

    @Test
    fun `stable session track replaces the generic URL without losing language`() {
        val generic = stream().copy(subtitles = listOf(subtitle("en"), subtitle("fr")))
        val state = PlayerPlaybackSelectionState(
            stream = generic,
            defaultAudioLanguage = "",
            subtitlesEnabled = true,
            defaultSubtitleLanguage = "fr",
            preferOriginalLanguage = false,
        )
        val session = generic.copy(
            subtitles = listOf(
                subtitle("en", trackId = "caption-en"),
                subtitle("fr", trackId = "caption-fr"),
            ),
        )

        state.updateStream(session, subtitlesEnabled = true, defaultSubtitleLanguage = "fr")

        assertEquals("caption-fr", state.selectedSubtitleKey)
    }

    @Test
    fun `codec and quality choices remain independent`() {
        val state = PlayerPlaybackSelectionState(
            stream = stream(),
            defaultAudioLanguage = "",
            subtitlesEnabled = false,
            defaultSubtitleLanguage = "",
            preferOriginalLanguage = false,
        )

        state.selectQuality("720p")
        state.selectCodec(AV1_CODEC_KEY)

        assertEquals("720p", state.selectedQuality)
        assertEquals(AV1_CODEC_KEY, state.selectedCodec)
    }

    @Test
    fun `server playback speed is applied and bounded`() {
        val configured = PlayerPlaybackSelectionState(
            stream = stream(),
            defaultAudioLanguage = "",
            subtitlesEnabled = false,
            defaultSubtitleLanguage = "",
            preferOriginalLanguage = false,
            defaultPlaybackSpeed = 1.5,
        )

        assertEquals(1.5f, configured.selectedSpeed, 0f)
        assertEquals(4f, normalizeDefaultPlaybackSpeed(9.0), 0f)
        assertEquals(0.25f, normalizeDefaultPlaybackSpeed(0.1), 0f)
        assertEquals(1f, normalizeDefaultPlaybackSpeed(Double.NaN), 0f)
    }

    private fun subtitle(
        language: String,
        trackId: String? = null,
    ) = StreamSubtitleSource(
        url = "https://example.test/$language.vtt",
        mimeType = "text/vtt",
        languageTag = language,
        displayLanguageName = language,
        isAutoGenerated = false,
        trackId = trackId,
    )

    private fun stream() = Stream(
        playbackContract = StreamPlaybackContract.ServerSabr,
        id = "video",
        title = "Video",
        uploaderName = "Channel",
        uploaderAvatarUrl = "",
        uploaderUrl = "",
        uploaderSubscriberCount = -1,
        uploaderVerified = false,
        thumbnailUrl = "",
        description = "",
        durationSeconds = 60,
        viewCount = -1,
        likeCount = -1,
        dislikeCount = -1,
        uploadedAtMillis = -1,
        hlsUrl = null,
        dashMpdUrl = null,
        progressiveUrl = null,
        serverDashManifestUrl = null,
        serverHlsManifestUrl = null,
        startPositionMillis = 0,
    )
}
