package dev.typetype.android.data.network.dto

import kotlinx.serialization.Serializable

@Serializable
data class StreamResponse(
    val id: String,
    val title: String,
    val uploaderName: String,
    val uploaderUrl: String,
    val uploaderAvatarUrl: String,
    val thumbnailUrl: String,
    val description: String,
    val duration: Long,
    val viewCount: Long,
    val likeCount: Long,
    val dislikeCount: Long,
    val uploadDate: String,
    val uploaded: Long,
    val uploaderSubscriberCount: Long,
    val uploaderVerified: Boolean,
    val category: String,
    val license: String,
    val visibility: String,
    val tags: List<String> = emptyList(),
    val streamType: String,
    val isShortFormContent: Boolean,
    val requiresMembership: Boolean,
    val startPosition: Long,
    val streamSegments: List<StreamSegmentItem> = emptyList(),
    val hlsUrl: String,
    val dashMpdUrl: String,
    val videoStreams: List<VideoStreamItem> = emptyList(),
    val audioStreams: List<AudioStreamItem> = emptyList(),
    val originalAudioTrackId: String? = null,
    val preferredDefaultAudioTrackId: String? = null,
    val videoOnlyStreams: List<VideoStreamItem> = emptyList(),
    val subtitles: List<SubtitleItem> = emptyList(),
    val previewFrames: List<PreviewFrameItem> = emptyList(),
    val sponsorBlockSegments: List<SponsorBlockSegmentItem> = emptyList(),
    val relatedStreams: List<VideoItem> = emptyList(),
    val publishedAt: Long? = null,
)

@Serializable
data class VideoStreamItem(
    val url: String,
    val mimeType: String,
    val format: String,
    val resolution: String,
    val bitrate: Int? = null,
    val codec: String? = null,
    val isVideoOnly: Boolean,
    val itag: Int,
    val width: Int,
    val height: Int,
    val fps: Int,
    val contentLength: Long,
    val initStart: Long = 0,
    val initEnd: Long = 0,
    val indexStart: Long = 0,
    val indexEnd: Long = 0,
)

@Serializable
data class AudioStreamItem(
    val url: String,
    val mimeType: String,
    val format: String,
    val bitrate: Int? = null,
    val codec: String? = null,
    val quality: String? = null,
    val itag: Int,
    val contentLength: Long,
    val initStart: Long = 0,
    val initEnd: Long = 0,
    val indexStart: Long = 0,
    val indexEnd: Long = 0,
    val audioTrackId: String? = null,
    val audioTrackName: String? = null,
    val audioLocale: String? = null,
    val isOriginal: Boolean = false,
)

@Serializable
data class SubtitleItem(
    val url: String,
    val mimeType: String,
    val languageTag: String,
    val displayLanguageName: String,
    val isAutoGenerated: Boolean,
)

@Serializable
data class PreviewFrameItem(
    val urls: List<String>,
    val frameWidth: Int,
    val frameHeight: Int,
    val totalCount: Int,
    val durationPerFrame: Int,
    val framesPerPageX: Int,
    val framesPerPageY: Int,
)

@Serializable
data class SponsorBlockSegmentItem(
    val startTime: Double,
    val endTime: Double,
    val category: String,
    val action: String,
)

@Serializable
data class StreamSegmentItem(
    val title: String,
    val startTimeSeconds: Int,
    val channelName: String? = null,
    val url: String? = null,
    val previewUrl: String? = null,
)
