package dev.typetype.android.feature.player.components

import dev.typetype.android.domain.stream.Stream
import dev.typetype.android.domain.stream.StreamAudioSource
import dev.typetype.android.domain.stream.StreamPlaybackContract
import dev.typetype.android.domain.stream.StreamSubtitleSource
import dev.typetype.android.domain.stream.StreamVideoSource
import dev.typetype.android.feature.player.DecoderSupport
import dev.typetype.android.feature.player.PlaybackCodecSupport
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class PlaybackOptionSourcesTest {
    @Test
    fun `codec and quality options are independent`() {
        val h264 = video("h264", "avc1.640028", bitrate = 5_000_000)
        val vp9 = video("vp9", "vp09.00.41.08", bitrate = 3_000_000)
        val audio = audio()
        val support = CodecSupport(
            videos = mapOf(h264.url to DecoderSupport.Hardware, vp9.url to DecoderSupport.Software),
            audios = mapOf(audio.url to DecoderSupport.Hardware),
        )

        val stream = stream(listOf(h264, vp9), audio)
        val codecs = stream.codecOptions(support)
        val h264Qualities = stream.qualityOptions("h264", support)

        assertEquals(listOf("H.264", "VP9"), codecs.map { it.label })
        assertEquals(
            listOf(DecoderSupport.Hardware, DecoderSupport.Software),
            codecs.map { it.decoderSupport },
        )
        assertEquals(listOf("1080p"), h264Qualities.map { it.label })
        assertTrue(h264Qualities.single().supportingLabel.orEmpty().contains("5 Mbps"))
    }

    @Test
    fun `unsupported codecs are absent from the picker`() {
        val h264 = video("h264", "avc1.640028", bitrate = 5_000_000)
        val av1 = video("av1", "av01.0.08M.08", bitrate = 2_000_000)
        val audio = audio()
        val support = CodecSupport(
            videos = mapOf(h264.url to DecoderSupport.Hardware),
            audios = mapOf(audio.url to DecoderSupport.Hardware),
        )

        val options = stream(listOf(h264, av1), audio).codecOptions(support)

        assertEquals(listOf("H.264"), options.map { it.label })
    }

    @Test
    fun `auto generated caption label is not duplicated`() {
        val stream = stream(emptyList(), audio()).copy(
            subtitles = listOf(
                StreamSubtitleSource(
                    url = "https://instance.example/captions/en.vtt",
                    mimeType = "text/vtt",
                    languageTag = "en",
                    displayLanguageName = "English (auto-generated)",
                    isAutoGenerated = true,
                    trackId = "en-auto",
                ),
            ),
        )

        val options = stream.captionOptions("Captions", "Auto-generated")

        assertEquals(listOf("English (Auto-generated)"), options.map { it.label })
    }

    private fun video(url: String, codec: String, bitrate: Int) = StreamVideoSource(
        url = url,
        mimeType = "video/mp4",
        codec = codec,
        resolution = "1080p",
        width = 1920,
        height = 1080,
        fps = 30,
        bitrate = bitrate,
        isVideoOnly = true,
    )

    private fun audio() = StreamAudioSource(
        url = "audio",
        mimeType = "audio/mp4",
        codec = "mp4a.40.2",
        bitrate = 128_000,
        quality = "medium",
        audioTrackId = null,
        audioTrackName = null,
        audioLocale = null,
        isOriginal = true,
    )

    private fun stream(videos: List<StreamVideoSource>, audio: StreamAudioSource) = Stream(
        playbackContract = StreamPlaybackContract.ProviderMedia,
        id = "video",
        title = "Video",
        uploaderName = "Channel",
        uploaderAvatarUrl = "avatar",
        uploaderUrl = "channel",
        uploaderSubscriberCount = 1,
        uploaderVerified = false,
        thumbnailUrl = "thumb",
        description = "",
        durationSeconds = 60,
        viewCount = 1,
        likeCount = 1,
        dislikeCount = 0,
        uploadedAtMillis = 1,
        hlsUrl = null,
        dashMpdUrl = null,
        progressiveUrl = null,
        serverDashManifestUrl = null,
        serverHlsManifestUrl = null,
        videoOnlyStreams = videos,
        audioStreams = listOf(audio),
        startPositionMillis = 0,
    )

    private class CodecSupport(
        private val videos: Map<String, DecoderSupport>,
        private val audios: Map<String, DecoderSupport>,
    ) : PlaybackCodecSupport {
        override fun video(source: StreamVideoSource): DecoderSupport =
            videos[source.url] ?: DecoderSupport.Unsupported

        override fun audio(source: StreamAudioSource): DecoderSupport =
            audios[source.url] ?: DecoderSupport.Unsupported
    }
}
