package dev.typetype.android.domain.usersettings

data class UserSettings(
    val defaultService: Int = 0,
    val defaultQuality: String = "1080p",
    val defaultPlaybackSpeed: Double = 1.0,
    val defaultLandingPage: String = "home",
    val autoplay: Boolean = true,
    val skipPlaylistAutoplayScreen: Boolean = false,
    val volume: Double = 1.0,
    val muted: Boolean = false,
    val subtitlesEnabled: Boolean = false,
    val defaultSubtitleLanguage: String = "",
    val defaultAudioLanguage: String = "",
    val captionStyles: CaptionStyles = CaptionStyles(),
    val preferOriginalLanguage: Boolean = false,
    val enableHighQualityPlayback: Boolean = false,
    val sponsorBlockMode: SponsorBlockMode = SponsorBlockMode.AutoSkip,
    val sponsorBlockCategoryActions: Map<String, SponsorBlockMode> =
        DEFAULT_SPONSOR_BLOCK_CATEGORY_ACTIONS,
    val sponsorBlockMinimumDuration: Int = 0,
    val sponsorBlockShowCurrentSegment: Boolean = true,
    val sponsorBlockShowChapters: Boolean = false,
    val sponsorBlockShowFullVideoLabels: Boolean = true,
    val sponsorBlockManualSkipOnFullVideo: Boolean = true,
    val sponsorBlockSkipNonMusicOnlyOnMusicVideos: Boolean = false,
    val sponsorBlockMuteInsteadOfSkip: Boolean = false,
    val hideHomeRecommendations: Boolean = false,
    val hideContinueWatching: Boolean = false,
    val hideRelatedVideos: Boolean = false,
    val hideComments: Boolean = false,
    val hideShorts: Boolean = false,
    val hideSubscriptionLiveStreams: Boolean = false,
    val supportsHideSubscriptionLiveStreams: Boolean = false,
    val disableWatchHistory: Boolean = false,
    val deArrowEnabled: Boolean = false,
    val deArrowTitleMode: String = "dearrow",
    val deArrowThumbnailMode: String = "dearrow_or_random",
    val deArrowTrustMode: String = "accepted",
    val accessMode: String = "unrestricted",
)
