package video.typetype.tv.player

import android.content.Context
import android.content.Intent
import video.typetype.sdk.core.AudioOnlyStream
import video.typetype.sdk.core.PlaybackSession
import video.typetype.sdk.core.StreamDetails
import video.typetype.sdk.core.SubtitleTrack
import video.typetype.sdk.core.UserSettings
import video.typetype.sdk.core.Video

internal object TvPlaybackStarter {
    fun play(
        context: Context,
        video: Video,
        stream: StreamDetails,
        session: PlaybackSession,
        subtitle: SubtitleTrack?,
        audioOnly: AudioOnlyStream?,
        settings: UserSettings,
    ): Boolean {
        val manifest = session.manifestUrl
        val isManifest = manifest != null
        if (isManifest && session.protocol.isNullOrBlank()) return false
        val videoItag = session.selectedVideoItag
        val audioItag = session.selectedAudioItag
        val videoMime = videoItag?.let { itag -> stream.videoOnlyStreams.firstOrNull { it.itag == itag }?.mimeType }
        val audioMime = audioItag?.let { itag -> stream.audioStreams.firstOrNull { it.itag == itag }?.mimeType }
        if (!isManifest && audioOnly == null &&
            (videoItag == null || audioItag == null || videoMime == null || audioMime == null)
        ) return false
        val policy = SponsorBlockPolicy.create(stream, settings)
        val intent = Intent(context, TypeTypePlaybackService::class.java)
            .setAction(ACTION_PLAY)
            .putExtra(SESSION_ID, session.sessionId)
            .putExtra(VIDEO_ID, stream.id.value)
            .putExtra(VIDEO_URL, video.url)
            .putExtra(TITLE, stream.title)
            .putExtra(THUMBNAIL_URL, stream.thumbnailUrl)
            .putExtra(DURATION, session.durationMilliseconds ?: stream.durationSeconds * 1_000L)
            .putExtra(VIDEO_ITAG, videoItag)
            .putExtra(AUDIO_ITAG, audioItag)
            .putExtra(AUDIO_TRACK_ID, session.audioTrackId)
            .putExtra(GENERATION, session.generation)
            .putExtra(START_TIME, session.startTimeMilliseconds)
            .putExtra(VIDEO_MIME, videoMime)
            .putExtra(AUDIO_MIME, audioMime)
            .putExtra(MANIFEST_URL, manifest)
            .putExtra(MANIFEST_PROTOCOL, session.protocol)
            .putExtra(AUDIO_ONLY_URL, audioOnly?.sourceUrl)
            .putExtra(AUDIO_ONLY_MIME, audioOnly?.mimeType)
            .putExtra(AUDIO_ONLY_KIND, audioOnly?.kind)
            .putExtra(TRACK_PROGRESS, !settings.disableWatchHistory)
            .putExtra(PLAYBACK_SPEED, settings.defaultPlaybackSpeed.toFloat().coerceIn(.25f, 4f))
            .putExtra(PLAYBACK_VOLUME, if (settings.muted) 0f else settings.volume.toFloat().coerceIn(0f, 1f))
            .putExtra(SUBTITLE_LANGUAGE, subtitle?.languageTag)
            .putExtra(SUBTITLE_NAME, subtitle?.displayName)
            .putExtra(SUBTITLE_AUTO, subtitle?.isAutoGenerated ?: false)
            .putExtra(SUBTITLE_SOURCE_LANGUAGE, subtitle?.sourceLanguage)
            .putExtra(SUBTITLE_TRANSLATION, subtitle?.translationLanguage)
            .putExtra(SUBTITLE_NAME_ID, subtitle?.name)
            .putSponsorBlockPolicy(policy)
        context.startService(intent)
        return true
    }
}
