@file:androidx.annotation.OptIn(markerClass = [androidx.media3.common.util.UnstableApi::class])

package video.typetype.tv.player

import android.net.Uri
import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.MimeTypes
import androidx.media3.datasource.ByteArrayDataSource
import androidx.media3.datasource.DataSource
import androidx.media3.exoplayer.source.MediaSource
import androidx.media3.exoplayer.source.SingleSampleMediaSource
import video.typetype.sdk.core.SubtitleRequest
import video.typetype.sdk.core.SubtitleTrack
import video.typetype.sdk.core.TypeTypeClient
import video.typetype.sdk.core.TypeTypeError
import video.typetype.sdk.core.TypeTypeResult
import video.typetype.sdk.core.VideoId

internal data class TvSubtitleSourceResult(
    val mediaSource: MediaSource?,
    val error: TypeTypeError?,
)

internal fun TypeTypeError.toSubtitleMessage(): String = when (this) {
    is TypeTypeError.Http -> buildString {
        append("Server error ").append(status)
        code?.let { append(" (").append(it).append(")") }
        requestId?.let { append(" · request ").append(it) }
    }
    is TypeTypeError.Network -> message
    is TypeTypeError.Serialization -> message
    is TypeTypeError.InvalidRequest -> message
    is TypeTypeError.Authentication -> message ?: "Authentication required"
}

internal suspend fun createTvSubtitleSource(
    client: TypeTypeClient,
    videoId: String,
    track: SubtitleTrack,
    durationMilliseconds: Long?,
): TvSubtitleSourceResult {
    val result = client.subtitles.fetch(
        SubtitleRequest(
            videoId = VideoId(videoId),
            language = track.languageTag,
            variant = if (track.isAutoGenerated) "auto" else "manual",
            format = "ttml",
            sourceLanguage = track.sourceLanguage,
            translation = track.translationLanguage,
            name = track.name,
        ),
    )
    val document = (result as? TypeTypeResult.Success)?.value
    if (document == null) {
        return TvSubtitleSourceResult(
            mediaSource = null,
            error = (result as? TypeTypeResult.Failure)?.error
                ?: TypeTypeError.Network("Subtitle response was empty", null),
        )
    }
    val bytes = document.content.toByteArray(Charsets.UTF_8)
    val dataSourceFactory = DataSource.Factory { ByteArrayDataSource(bytes) }
    val configuration = MediaItem.SubtitleConfiguration.Builder(
        Uri.parse("typetype-subtitle://$videoId/${track.languageTag}"),
    )
        .setMimeType(MimeTypes.APPLICATION_TTML)
        .setLanguage(track.languageTag)
        .setLabel(track.displayName ?: track.languageTag)
        .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
        .build()
    return TvSubtitleSourceResult(
        mediaSource = SingleSampleMediaSource.Factory(dataSourceFactory)
            .createMediaSource(configuration, durationMilliseconds ?: C.TIME_UNSET),
        error = null,
    )
}
